
networks:
  default:
    name: ${DEFAULT_NETWORK:-dokploy-network}
    external: ${DEFAULT_NETWORK_EXTERNAL:-true}

volumes:
  tpl_data:
    name: ${TPL_DATA_VOLUME_NAME:-tpl_data}
    external: ${TPL_DATA_VOLUME_EXTERNAL:-false}
  tpl_logs:
    name: ${TPL_LOGS_VOLUME_NAME:-tpl_logs}
    external: ${TPL_LOGS_VOLUME_EXTERNAL:-false}

services:
  tpl:
    image: ${TPL_IMAGE:-tpl/tpl:latest}
    pull_policy: ${TPL_PULL_POLICY:-always}
    restart: ${TPL_RESTART:-unless-stopped}
    privileged: ${TPL_PRIVILEGED:-true}
    environment:
      - TZ
      - http_proxy
      - https_proxy
      - no_proxy
    volumes:
      - ${TPL_MOUNT_DATA:-tpl_data}:/var/tpl
      - ${TPL_MOUNT_LOGS:-tpl_logs}:/var/log/tpl
      - ${DOCKER_RUNTIME_SOCKET:-/var/run/docker.sock}:/var/run/docker.sock
    labels:
      traefik.enable: "true"
      traefik.http.services.tpl.loadbalancer.server.port: 9000
      traefik.http.routers.tpl.entrypoints: ${TPL_TRAEFIK_ENTRYPOINTS:-web}
      traefik.http.routers.tpl.rule: Host(`${TPL_DOMAIN:-example.com}`) && PathPrefix(`${TPL_BASE_PATH:-/}`)
      traefik.http.routers.tpl.service: tpl
      traefik.http.routers.tpl.middlewares: "${TPL_TRAEFIK_MIDDLEWARES:-}"
      traefik.http.routers.tpl.tls: "${TPL_TRAEFIK_TLS_ENABLED:-false}"
      traefik.http.routers.tpl.tls.certresolver: ${TPL_TRAEFIK_TLS_CERTRESOLVER:-letsencrypt}
      ## Homepage configuration
      homepage.group: ${TPL_HOMEPAGE_GROUP:-Infra}
      homepage.name: ${TPL_HOMEPAGE_NAME:-Tpl}
      homepage.icon: ${TPL_HOMEPAGE_ICON:-tpl.png}
      homepage.href: ${TPL_HOMEPAGE_HREF:-http://example.com}
      homepage.description: ${TPL_HOMEPAGE_DESCRIPTION:-}
      homepage.siteMonitor: ${TPL_HOMEPAGE_SITEMONITOR:-http://example.com}
      homepage.ping: ${TPL_HOMEPAGE_PING:-http://tpl:9000}
