# name: storage # Not supported by Docker Swarm

volumes:
  rustfs_data:
    driver: local
networks:
  default:
    name: ${DEFAULT_NETWORK:-dokploy-network}
    external: true

services:
  rustfs:
    image: rustfs/rustfs:latest
    restart: unless-stopped
    privileged: true
    environment:
      - TZ
      - http_proxy
      - https_proxy
      - no_proxy
      - RUSTFS_ACCESS_KEY
      - RUSTFS_SECRET_KEY
      - RUSTFS_VOLUMES=/data
      - RUSTFS_ADDRESS=0.0.0.0:9000
      - RUSTFS_CONSOLE_ENABLE=true
      - RUSTFS_CONSOLE_ADDRESS=0.0.0.0:9001
    volumes:
      - ${RUSTFS_DATA_DIR:-rustfs_data}:/data
    networks:
      - default
    ## Deploy
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        # HTTPS router
        - "traefik.http.services.rustfs-s3.loadbalancer.server.port=9000"
        - "traefik.http.routers.rustfs-s3.rule=Host(`${RUSTFS_S3_DOMAIN}`)"
        - "traefik.http.routers.rustfs-s3.service=rustfs-s3"
        - "traefik.http.routers.rustfs-s3.entrypoints=web"
        # RustFS Console HTTPS router
        - "traefik.http.services.rustfs-console.loadbalancer.server.port=9001"
        - "traefik.http.routers.rustfs-console.rule=Host(`${RUSTFS_S3_DOMAIN}`) && PathPrefix(`/rustfs`)"
        - "traefik.http.routers.rustfs-console.service=rustfs-console"
        - "traefik.http.routers.rustfs-console.entrypoints=web"
        # Homepage
        - homepage.group=${RUSTFS_HOMEPAGE_GROUP:-Storage}
        - homepage.name=${RUSTFS_HOMEPAGE_NAME:-RustFS}
        - homepage.icon=${RUSTFS_HOMEPAGE_ICON:-rustfs.png}
        - homepage.href=${RUSTFS_HOMEPAGE_HREF:-http://${RUSTFS_S3_DOMAIN}/rustfs/}

