networks:
  default:
    name: ${DEFAULT_NETWORK_NAME:-huly-network}
    external: ${DEFAULT_NETWORK_EXTERNAL:-false}


services:
  rekoni:
    image: ${HULY_REKONI_IMAGE:-docker.io/hardcoreeng/rekoni-service:v0.7.426}
    restart: ${HULY_RESTART:-unless-stopped}
    privileged: ${HULY_PRIVILEGED:-false}
    env_file:
      - ${HULY_REKONI_ENV_FILE:-.env.example}
    environment:
      - TZ=${TZ:-America/Montreal}
      - SECRET=${HULY_SECRET:-ChangeMe}
    networks:
      - default
    deploy:
      mode: ${HULY_REKONI_DEPLOY_MODE:-replicated}
      replicas: ${HULY_REKONI_DEPLOY_REPLICAS:-1}
      resources:
        limits:
          memory: ${HULY_REKONI_MEMORY_LIMIT:-512M}
      placement:
        constraints:
          - ${HULY_REKONI_PLACEMENT_CONSTRAINTS:-node.platform.os==linux}
      restart_policy:
        condition: ${HULY_REKONI_RESTART_POLICY_CONDITION:-any}
        delay: ${HULY_REKONI_RESTART_POLICY_DELAY:-5s}
        max_attempts: ${HULY_REKONI_RESTART_POLICY_MAX_ATTEMPTS:-3}
      labels:
        - "traefik.enable=${HULY_TRAEFIK_LABELS_SWARM_ENABLE:-true}"
        - "traefik.http.services.${APP_NAME:-huly}-rekoni.loadbalancer.server.port=${HULY_REKONI_PORT:-4004}"
        - "traefik.http.routers.${APP_NAME:-huly}-rekoni.entrypoints=${HULY_ENTRYPOINTS:-web}"
        - "traefik.http.routers.${APP_NAME:-huly}-rekoni.rule=Host(`${HULY_DOMAIN:-huly.example.com}`) && PathPrefix(`/_rekoni`)"
        - "traefik.http.routers.${APP_NAME:-huly}-rekoni.service=${APP_NAME:-huly}-rekoni"
        - "traefik.http.routers.${APP_NAME:-huly}-rekoni.middlewares=${APP_NAME:-huly}-rekoni-strip"
        - "traefik.http.routers.${APP_NAME:-huly}-rekoni.priority=100"
        - "traefik.http.routers.${APP_NAME:-huly}-rekoni.tls=${HULY_TLS_ENABLED:-false}"
        - "traefik.http.routers.${APP_NAME:-huly}-rekoni.tls.certresolver=${HULY_TLS_CERTRESOLVER:-letsencrypt}"
        - "traefik.http.middlewares.${APP_NAME:-huly}-rekoni-strip.stripprefix.prefixes=/_rekoni"
    labels:
      - "traefik.enable=${HULY_TRAEFIK_LABELS_DOCKER_ENABLE:-true}"
      - "traefik.http.services.${APP_NAME:-huly}-rekoni.loadbalancer.server.port=${HULY_REKONI_PORT:-4004}"
      - "traefik.http.routers.${APP_NAME:-huly}-rekoni.entrypoints=${HULY_ENTRYPOINTS:-web}"
      - "traefik.http.routers.${APP_NAME:-huly}-rekoni.rule=Host(`${HULY_DOMAIN:-huly.example.com}`) && PathPrefix(`/_rekoni`)"
      - "traefik.http.routers.${APP_NAME:-huly}-rekoni.service=${APP_NAME:-huly}-rekoni"
      - "traefik.http.routers.${APP_NAME:-huly}-rekoni.middlewares=${APP_NAME:-huly}-rekoni-strip"
      - "traefik.http.routers.${APP_NAME:-huly}-rekoni.priority=100"
      - "traefik.http.routers.${APP_NAME:-huly}-rekoni.tls=${HULY_TLS_ENABLED:-false}"
      - "traefik.http.routers.${APP_NAME:-huly}-rekoni.tls.certresolver=${HULY_TLS_CERTRESOLVER:-letsencrypt}"
      - "traefik.http.middlewares.${APP_NAME:-huly}-rekoni-strip.stripprefix.prefixes=/_rekoni"

  transactor:
    image: ${HULY_TRANSACTOR_IMAGE:-docker.io/hardcoreeng/transactor:v0.7.426}
    restart: ${HULY_RESTART:-unless-stopped}
    privileged: ${HULY_PRIVILEGED:-false}
    env_file:
      - ${HULY_TRANSACTOR_ENV_FILE:-.env.example}
    environment:
      - TZ=${TZ:-America/Montreal}
      - SERVER_PORT=${HULY_TRANSACTOR_PORT:-3333}
      - SERVER_SECRET=${HULY_SECRET:-ChangeMe}
      - DB_URL=${HULY_CR_DB_URL:-postgres://huly:ChangeMe@postgresql:26257/huly}
      - STORAGE_CONFIG=${HULY_STORAGE_CONFIG:-minio|minio:9000?accessKey=ChangeMe&secretKey=ChangeMe&rootBucket=huly}
      - FRONT_URL=${HULY_HTTP_SCHEME:-https}://${HULY_DOMAIN:-huly.example.com}
      - ACCOUNTS_URL=http://account:3000
      - FULLTEXT_URL=http://fulltext:4700
      - STATS_URL=http://stats:4900
      - LAST_NAME_FIRST=${HULY_LAST_NAME_FIRST:-true}
      - QUEUE_CONFIG=${HULY_QUEUE_CONFIG:-kafka:9092}
      - MAIL_URL=${HULY_MAIL_URL:-http://mail:8097}
    networks:
      - default
    deploy:
      mode: ${HULY_TRANSACTOR_DEPLOY_MODE:-replicated}
      replicas: ${HULY_TRANSACTOR_DEPLOY_REPLICAS:-1}
      resources:
        limits:
          memory: ${HULY_TRANSACTOR_MEMORY_LIMIT:-1G}
      placement:
        constraints:
          - ${HULY_TRANSACTOR_PLACEMENT_CONSTRAINTS:-node.platform.os==linux}
      restart_policy:
        condition: ${HULY_TRANSACTOR_RESTART_POLICY_CONDITION:-any}
        delay: ${HULY_TRANSACTOR_RESTART_POLICY_DELAY:-5s}
        max_attempts: ${HULY_TRANSACTOR_RESTART_POLICY_MAX_ATTEMPTS:-3}
      labels:
        - "traefik.enable=${HULY_TRAEFIK_LABELS_SWARM_ENABLE:-true}"
        - "traefik.http.services.${APP_NAME:-huly}-transactor.loadbalancer.server.port=${HULY_TRANSACTOR_PORT:-3333}"
        - "traefik.http.routers.${APP_NAME:-huly}-transactor.entrypoints=${HULY_ENTRYPOINTS:-web}"
        - "traefik.http.routers.${APP_NAME:-huly}-transactor.rule=Host(`${HULY_DOMAIN:-huly.example.com}`) && PathPrefix(`/_transactor`)"
        - "traefik.http.routers.${APP_NAME:-huly}-transactor.service=${APP_NAME:-huly}-transactor"
        - "traefik.http.routers.${APP_NAME:-huly}-transactor.middlewares=${APP_NAME:-huly}-transactor-strip"
        - "traefik.http.routers.${APP_NAME:-huly}-transactor.priority=100"
        - "traefik.http.routers.${APP_NAME:-huly}-transactor.tls=${HULY_TLS_ENABLED:-false}"
        - "traefik.http.routers.${APP_NAME:-huly}-transactor.tls.certresolver=${HULY_TLS_CERTRESOLVER:-letsencrypt}"
        - "traefik.http.middlewares.${APP_NAME:-huly}-transactor-strip.stripprefix.prefixes=/_transactor"
        - "traefik.http.routers.${APP_NAME:-huly}-transactor-jwt.entrypoints=${HULY_ENTRYPOINTS:-web}"
        - "traefik.http.routers.${APP_NAME:-huly}-transactor-jwt.rule=Host(`${HULY_DOMAIN:-huly.example.com}`) && PathPrefix(`/eyJ`)"
        - "traefik.http.routers.${APP_NAME:-huly}-transactor-jwt.service=${APP_NAME:-huly}-transactor"
        - "traefik.http.routers.${APP_NAME:-huly}-transactor-jwt.middlewares=${HULY_MIDDLEWARES:-}"
        - "traefik.http.routers.${APP_NAME:-huly}-transactor-jwt.priority=110"
        - "traefik.http.routers.${APP_NAME:-huly}-transactor-jwt.tls=${HULY_TLS_ENABLED:-false}"
        - "traefik.http.routers.${APP_NAME:-huly}-transactor-jwt.tls.certresolver=${HULY_TLS_CERTRESOLVER:-letsencrypt}"
    labels:
      - "traefik.enable=${HULY_TRAEFIK_LABELS_DOCKER_ENABLE:-true}"
      - "traefik.http.services.${APP_NAME:-huly}-transactor.loadbalancer.server.port=${HULY_TRANSACTOR_PORT:-3333}"
      - "traefik.http.routers.${APP_NAME:-huly}-transactor.entrypoints=${HULY_ENTRYPOINTS:-web}"
      - "traefik.http.routers.${APP_NAME:-huly}-transactor.rule=Host(`${HULY_DOMAIN:-huly.example.com}`) && PathPrefix(`/_transactor`)"
      - "traefik.http.routers.${APP_NAME:-huly}-transactor.service=${APP_NAME:-huly}-transactor"
      - "traefik.http.routers.${APP_NAME:-huly}-transactor.middlewares=${APP_NAME:-huly}-transactor-strip"
      - "traefik.http.routers.${APP_NAME:-huly}-transactor.priority=100"
      - "traefik.http.routers.${APP_NAME:-huly}-transactor.tls=${HULY_TLS_ENABLED:-false}"
      - "traefik.http.routers.${APP_NAME:-huly}-transactor.tls.certresolver=${HULY_TLS_CERTRESOLVER:-letsencrypt}"
      - "traefik.http.middlewares.${APP_NAME:-huly}-transactor-strip.stripprefix.prefixes=/_transactor"
      - "traefik.http.routers.${APP_NAME:-huly}-transactor-jwt.entrypoints=${HULY_ENTRYPOINTS:-web}"
      - "traefik.http.routers.${APP_NAME:-huly}-transactor-jwt.rule=Host(`${HULY_DOMAIN:-huly.example.com}`) && PathPrefix(`/eyJ`)"
      - "traefik.http.routers.${APP_NAME:-huly}-transactor-jwt.service=${APP_NAME:-huly}-transactor"
      - "traefik.http.routers.${APP_NAME:-huly}-transactor-jwt.middlewares=${HULY_MIDDLEWARES:-}"
      - "traefik.http.routers.${APP_NAME:-huly}-transactor-jwt.priority=110"
      - "traefik.http.routers.${APP_NAME:-huly}-transactor-jwt.tls=${HULY_TLS_ENABLED:-false}"
      - "traefik.http.routers.${APP_NAME:-huly}-transactor-jwt.tls.certresolver=${HULY_TLS_CERTRESOLVER:-letsencrypt}"

  collaborator:
    image: ${HULY_COLLABORATOR_IMAGE:-docker.io/hardcoreeng/collaborator:v0.7.426}
    restart: ${HULY_RESTART:-unless-stopped}
    privileged: ${HULY_PRIVILEGED:-false}
    env_file:
      - ${HULY_COLLABORATOR_ENV_FILE:-.env.example}
    environment:
      - TZ=${TZ:-America/Montreal}
      - COLLABORATOR_PORT=${HULY_COLLABORATOR_PORT:-3078}
      - SECRET=${HULY_SECRET:-ChangeMe}
      - ACCOUNTS_URL=http://account:3000
      - STATS_URL=http://stats:4900
      - STORAGE_CONFIG=${HULY_STORAGE_CONFIG:-minio|minio:9000?accessKey=ChangeMe&secretKey=ChangeMe&rootBucket=huly}
    networks:
      - default
    deploy:
      mode: ${HULY_COLLABORATOR_DEPLOY_MODE:-replicated}
      replicas: ${HULY_COLLABORATOR_DEPLOY_REPLICAS:-1}
      resources:
        limits:
          memory: ${HULY_COLLABORATOR_MEMORY_LIMIT:-1G}
      placement:
        constraints:
          - ${HULY_COLLABORATOR_PLACEMENT_CONSTRAINTS:-node.platform.os==linux}
      restart_policy:
        condition: ${HULY_COLLABORATOR_RESTART_POLICY_CONDITION:-any}
        delay: ${HULY_COLLABORATOR_RESTART_POLICY_DELAY:-5s}
        max_attempts: ${HULY_COLLABORATOR_RESTART_POLICY_MAX_ATTEMPTS:-3}
      labels:
        - "traefik.enable=${HULY_TRAEFIK_LABELS_SWARM_ENABLE:-true}"
        - "traefik.http.services.${APP_NAME:-huly}-collaborator.loadbalancer.server.port=${HULY_COLLABORATOR_PORT:-3078}"
        - "traefik.http.routers.${APP_NAME:-huly}-collaborator.entrypoints=${HULY_ENTRYPOINTS:-web}"
        - "traefik.http.routers.${APP_NAME:-huly}-collaborator.rule=Host(`${HULY_DOMAIN:-huly.example.com}`) && PathPrefix(`/_collaborator`)"
        - "traefik.http.routers.${APP_NAME:-huly}-collaborator.service=${APP_NAME:-huly}-collaborator"
        - "traefik.http.routers.${APP_NAME:-huly}-collaborator.middlewares=${APP_NAME:-huly}-collaborator-strip"
        - "traefik.http.routers.${APP_NAME:-huly}-collaborator.priority=100"
        - "traefik.http.routers.${APP_NAME:-huly}-collaborator.tls=${HULY_TLS_ENABLED:-false}"
        - "traefik.http.routers.${APP_NAME:-huly}-collaborator.tls.certresolver=${HULY_TLS_CERTRESOLVER:-letsencrypt}"
        - "traefik.http.middlewares.${APP_NAME:-huly}-collaborator-strip.stripprefix.prefixes=/_collaborator"
    labels:
      - "traefik.enable=${HULY_TRAEFIK_LABELS_DOCKER_ENABLE:-true}"
      - "traefik.http.services.${APP_NAME:-huly}-collaborator.loadbalancer.server.port=${HULY_COLLABORATOR_PORT:-3078}"
      - "traefik.http.routers.${APP_NAME:-huly}-collaborator.entrypoints=${HULY_ENTRYPOINTS:-web}"
      - "traefik.http.routers.${APP_NAME:-huly}-collaborator.rule=Host(`${HULY_DOMAIN:-huly.example.com}`) && PathPrefix(`/_collaborator`)"
      - "traefik.http.routers.${APP_NAME:-huly}-collaborator.service=${APP_NAME:-huly}-collaborator"
      - "traefik.http.routers.${APP_NAME:-huly}-collaborator.middlewares=${APP_NAME:-huly}-collaborator-strip"
      - "traefik.http.routers.${APP_NAME:-huly}-collaborator.priority=100"
      - "traefik.http.routers.${APP_NAME:-huly}-collaborator.tls=${HULY_TLS_ENABLED:-false}"
      - "traefik.http.routers.${APP_NAME:-huly}-collaborator.tls.certresolver=${HULY_TLS_CERTRESOLVER:-letsencrypt}"
      - "traefik.http.middlewares.${APP_NAME:-huly}-collaborator-strip.stripprefix.prefixes=/_collaborator"

  account:
    image: ${HULY_ACCOUNT_IMAGE:-docker.io/hardcoreeng/account:v0.7.426}
    restart: ${HULY_RESTART:-unless-stopped}
    privileged: ${HULY_PRIVILEGED:-false}
    env_file:
      - ${HULY_ACCOUNT_ENV_FILE:-.env.example}
    environment:
      - TZ=${TZ:-America/Montreal}
      - SERVER_PORT=${HULY_ACCOUNT_PORT:-3000}
      - ACCOUNT_PORT=${HULY_ACCOUNT_PORT:-3000}
      - SERVER_SECRET=${HULY_SECRET:-ChangeMe}
      - DB_URL=${HULY_CR_DB_URL:-postgres://huly:ChangeMe@postgresql:26257/huly}
      - TRANSACTOR_URL=ws://transactor:3333;${HULY_WS_SCHEME:-wss}://${HULY_DOMAIN:-huly.example.com}/_transactor
      - STORAGE_CONFIG=${HULY_STORAGE_CONFIG:-minio|minio:9000?accessKey=ChangeMe&secretKey=ChangeMe&rootBucket=huly}
      - FRONT_URL=${HULY_HTTP_SCHEME:-https}://${HULY_DOMAIN:-huly.example.com}
      - STATS_URL=${HULY_HTTP_SCHEME:-https}://${HULY_DOMAIN:-huly.example.com}/_stats
      - MODEL_ENABLED=${HULY_MODEL_ENABLED:-*}
      - ACCOUNTS_URL=${HULY_HTTP_SCHEME:-https}://${HULY_DOMAIN:-huly.example.com}/_accounts
      - QUEUE_CONFIG=${HULY_QUEUE_CONFIG:-kafka:9092}
      - MAIL_URL=${HULY_MAIL_URL:-http://mail:8097}
      - OPENID_CLIENT_ID=${HULY_OPENID_CLIENT_ID:-}
      - OPENID_CLIENT_SECRET=${HULY_OPENID_CLIENT_SECRET:-}
      - OPENID_ISSUER=${HULY_OPENID_ISSUER:-}
      - OPENID_DISPLAY_NAME=${HULY_OPENID_DISPLAY_NAME:-}
      - DISABLE_SIGNUP=${HULY_DISABLE_SIGNUP:-false}
    networks:
      - default
    deploy:
      mode: ${HULY_ACCOUNT_DEPLOY_MODE:-replicated}
      replicas: ${HULY_ACCOUNT_DEPLOY_REPLICAS:-1}
      resources:
        limits:
          memory: ${HULY_ACCOUNT_MEMORY_LIMIT:-1G}
      placement:
        constraints:
          - ${HULY_ACCOUNT_PLACEMENT_CONSTRAINTS:-node.platform.os==linux}
      restart_policy:
        condition: ${HULY_ACCOUNT_RESTART_POLICY_CONDITION:-any}
        delay: ${HULY_ACCOUNT_RESTART_POLICY_DELAY:-5s}
        max_attempts: ${HULY_ACCOUNT_RESTART_POLICY_MAX_ATTEMPTS:-3}
      labels:
        - "traefik.enable=${HULY_TRAEFIK_LABELS_SWARM_ENABLE:-true}"
        - "traefik.http.services.${APP_NAME:-huly}-account.loadbalancer.server.port=${HULY_ACCOUNT_PORT:-3000}"
        - "traefik.http.routers.${APP_NAME:-huly}-account.entrypoints=${HULY_ENTRYPOINTS:-web}"
        - "traefik.http.routers.${APP_NAME:-huly}-account.rule=Host(`${HULY_DOMAIN:-huly.example.com}`) && PathPrefix(`/_accounts`)"
        - "traefik.http.routers.${APP_NAME:-huly}-account.service=${APP_NAME:-huly}-account"
        - "traefik.http.routers.${APP_NAME:-huly}-account.middlewares=${APP_NAME:-huly}-account-strip"
        - "traefik.http.routers.${APP_NAME:-huly}-account.priority=100"
        - "traefik.http.routers.${APP_NAME:-huly}-account.tls=${HULY_TLS_ENABLED:-false}"
        - "traefik.http.routers.${APP_NAME:-huly}-account.tls.certresolver=${HULY_TLS_CERTRESOLVER:-letsencrypt}"
        - "traefik.http.middlewares.${APP_NAME:-huly}-account-strip.stripprefix.prefixes=/_accounts"
    labels:
      - "traefik.enable=${HULY_TRAEFIK_LABELS_DOCKER_ENABLE:-true}"
      - "traefik.http.services.${APP_NAME:-huly}-account.loadbalancer.server.port=${HULY_ACCOUNT_PORT:-3000}"
      - "traefik.http.routers.${APP_NAME:-huly}-account.entrypoints=${HULY_ENTRYPOINTS:-web}"
      - "traefik.http.routers.${APP_NAME:-huly}-account.rule=Host(`${HULY_DOMAIN:-huly.example.com}`) && PathPrefix(`/_accounts`)"
      - "traefik.http.routers.${APP_NAME:-huly}-account.service=${APP_NAME:-huly}-account"
      - "traefik.http.routers.${APP_NAME:-huly}-account.middlewares=${APP_NAME:-huly}-account-strip"
      - "traefik.http.routers.${APP_NAME:-huly}-account.priority=100"
      - "traefik.http.routers.${APP_NAME:-huly}-account.tls=${HULY_TLS_ENABLED:-false}"
      - "traefik.http.routers.${APP_NAME:-huly}-account.tls.certresolver=${HULY_TLS_CERTRESOLVER:-letsencrypt}"
      - "traefik.http.middlewares.${APP_NAME:-huly}-account-strip.stripprefix.prefixes=/_accounts"

  workspace:
    image: ${HULY_WORKSPACE_IMAGE:-docker.io/hardcoreeng/workspace:v0.7.426}
    restart: ${HULY_RESTART:-unless-stopped}
    privileged: ${HULY_PRIVILEGED:-false}
    env_file:
      - ${HULY_WORKSPACE_ENV_FILE:-.env.example}
    environment:
      - TZ=${TZ:-America/Montreal}
      - SERVER_SECRET=${HULY_SECRET:-ChangeMe}
      - DB_URL=${HULY_CR_DB_URL:-postgres://huly:ChangeMe@postgresql:26257/huly}
      - TRANSACTOR_URL=ws://transactor:3333;${HULY_WS_SCHEME:-wss}://${HULY_DOMAIN:-huly.example.com}/_transactor
      - STORAGE_CONFIG=${HULY_STORAGE_CONFIG:-minio|minio:9000?accessKey=ChangeMe&secretKey=ChangeMe&rootBucket=huly}
      - MODEL_ENABLED=${HULY_MODEL_ENABLED:-*}
      - ACCOUNTS_URL=http://account:3000
      - STATS_URL=http://stats:4900
      - QUEUE_CONFIG=${HULY_QUEUE_CONFIG:-kafka:9092}
      - ACCOUNTS_DB_URL=${HULY_CR_DB_URL:-postgres://huly:ChangeMe@postgresql:26257/huly}
      - INIT_REPO_DIR=${HULY_INIT_REPO_DIR:-}
    networks:
      - default
    deploy:
      mode: ${HULY_WORKSPACE_DEPLOY_MODE:-replicated}
      replicas: ${HULY_WORKSPACE_DEPLOY_REPLICAS:-1}
      resources:
        limits:
          memory: ${HULY_WORKSPACE_MEMORY_LIMIT:-1G}
      placement:
        constraints:
          - ${HULY_WORKSPACE_PLACEMENT_CONSTRAINTS:-node.platform.os==linux}
      restart_policy:
        condition: ${HULY_WORKSPACE_RESTART_POLICY_CONDITION:-any}
        delay: ${HULY_WORKSPACE_RESTART_POLICY_DELAY:-5s}
        max_attempts: ${HULY_WORKSPACE_RESTART_POLICY_MAX_ATTEMPTS:-3}

  front:
    image: ${HULY_FRONT_IMAGE:-docker.io/hardcoreeng/front:v0.7.426}
    restart: ${HULY_RESTART:-unless-stopped}
    privileged: ${HULY_PRIVILEGED:-false}
    env_file:
      - ${HULY_FRONT_ENV_FILE:-.env.example}
    environment:
      - TZ=${TZ:-America/Montreal}
      - SERVER_PORT=${HULY_FRONT_PORT:-8080}
      - SERVER_SECRET=${HULY_SECRET:-ChangeMe}
      - LOVE_ENDPOINT=${HULY_HTTP_SCHEME:-https}://${HULY_DOMAIN:-huly.example.com}/_love
      - ACCOUNTS_URL=${HULY_HTTP_SCHEME:-https}://${HULY_DOMAIN:-huly.example.com}/_accounts
      - ACCOUNTS_URL_INTERNAL=http://account:3000
      - REKONI_URL=${HULY_HTTP_SCHEME:-https}://${HULY_DOMAIN:-huly.example.com}/_rekoni
      - CALENDAR_URL=${HULY_HTTP_SCHEME:-https}://${HULY_DOMAIN:-huly.example.com}/_calendar
      - GMAIL_URL=${HULY_HTTP_SCHEME:-https}://${HULY_DOMAIN:-huly.example.com}/_gmail
      - TELEGRAM_URL=${HULY_HTTP_SCHEME:-https}://${HULY_DOMAIN:-huly.example.com}/_telegram
      - STATS_URL=${HULY_HTTP_SCHEME:-https}://${HULY_DOMAIN:-huly.example.com}/_stats
      - UPLOAD_URL=${HULY_UPLOAD_URL:-/files}
      - STREAM_URL=${HULY_STREAM_URL:-https://huly.example.com/recording}
      - FILES_URL=${HULY_FILES_URL:-https://huly.example.com/_datalake/blob/:workspace/:blobId/:filename}
      - DATALAKE_URL=${HULY_DATALAKE_URL:-https://huly.example.com/_datalake}
      - ELASTIC_URL=${HULY_ELASTIC_URL:-http://elasticsearch:9200}
      - COLLABORATOR_URL=${HULY_WS_SCHEME:-wss}://${HULY_DOMAIN:-huly.example.com}/_collaborator
      - STORAGE_CONFIG=${HULY_STORAGE_CONFIG:-minio|minio:9000?accessKey=ChangeMe&secretKey=ChangeMe&rootBucket=huly}
      - TITLE=${HULY_TITLE:-Huly Self Host}
      - DEFAULT_LANGUAGE=${HULY_DEFAULT_LANGUAGE:-en}
      - LAST_NAME_FIRST=${HULY_LAST_NAME_FIRST:-true}
      - DESKTOP_UPDATES_CHANNEL=${HULY_DESKTOP_CHANNEL:-0.7.426}
      - DISABLED_FEATURES=${HULY_DISABLED_FEATURES:-auto-translate,mailboxes}
      - DISABLE_SIGNUP=${HULY_DISABLE_SIGNUP:-false}
      - HIDE_LOCAL_LOGIN=${HULY_HIDE_LOCAL_LOGIN:-false}
    networks:
      - default
    deploy:
      mode: ${HULY_FRONT_DEPLOY_MODE:-replicated}
      replicas: ${HULY_FRONT_DEPLOY_REPLICAS:-1}
      resources:
        limits:
          memory: ${HULY_FRONT_MEMORY_LIMIT:-1G}
      placement:
        constraints:
          - ${HULY_FRONT_PLACEMENT_CONSTRAINTS:-node.platform.os==linux}
      restart_policy:
        condition: ${HULY_FRONT_RESTART_POLICY_CONDITION:-any}
        delay: ${HULY_FRONT_RESTART_POLICY_DELAY:-5s}
        max_attempts: ${HULY_FRONT_RESTART_POLICY_MAX_ATTEMPTS:-3}
      labels:
        - "traefik.enable=${HULY_TRAEFIK_LABELS_SWARM_ENABLE:-true}"
        - "traefik.http.services.${APP_NAME:-huly}-front.loadbalancer.server.port=${HULY_FRONT_PORT:-8080}"
        - "traefik.http.routers.${APP_NAME:-huly}-front.entrypoints=${HULY_ENTRYPOINTS:-web}"
        - "traefik.http.routers.${APP_NAME:-huly}-front.rule=Host(`${HULY_DOMAIN:-huly.example.com}`)"
        - "traefik.http.routers.${APP_NAME:-huly}-front.service=${APP_NAME:-huly}-front"
        - "traefik.http.routers.${APP_NAME:-huly}-front.middlewares=${HULY_MIDDLEWARES:-}"
        - "traefik.http.routers.${APP_NAME:-huly}-front.priority=1"
        - "traefik.http.routers.${APP_NAME:-huly}-front.tls=${HULY_TLS_ENABLED:-false}"
        - "traefik.http.routers.${APP_NAME:-huly}-front.tls.certresolver=${HULY_TLS_CERTRESOLVER:-letsencrypt}"
        - "homepage.group=${HULY_HOMEPAGE_GROUP:-Productivity}"
        - "homepage.name=${HULY_HOMEPAGE_NAME:-Huly}"
        - "homepage.icon=${HULY_HOMEPAGE_ICON:-si-linear}"
        - "homepage.href=${HULY_HOMEPAGE_URL:-}"
        - "homepage.description=${HULY_HOMEPAGE_DESCRIPTION:-All-in-one project management}"
        - "homepage.siteMonitor=${HULY_HOMEPAGE_SITEMONITOR:-http://front:8080}"
    labels:
      - "traefik.enable=${HULY_TRAEFIK_LABELS_DOCKER_ENABLE:-true}"
      - "traefik.http.services.${APP_NAME:-huly}-front.loadbalancer.server.port=${HULY_FRONT_PORT:-8080}"
      - "traefik.http.routers.${APP_NAME:-huly}-front.entrypoints=${HULY_ENTRYPOINTS:-web}"
      - "traefik.http.routers.${APP_NAME:-huly}-front.rule=Host(`${HULY_DOMAIN:-huly.example.com}`)"
      - "traefik.http.routers.${APP_NAME:-huly}-front.service=${APP_NAME:-huly}-front"
      - "traefik.http.routers.${APP_NAME:-huly}-front.middlewares=${HULY_MIDDLEWARES:-}"
      - "traefik.http.routers.${APP_NAME:-huly}-front.priority=1"
      - "traefik.http.routers.${APP_NAME:-huly}-front.tls=${HULY_TLS_ENABLED:-false}"
      - "traefik.http.routers.${APP_NAME:-huly}-front.tls.certresolver=${HULY_TLS_CERTRESOLVER:-letsencrypt}"
      - "homepage.group=${HULY_HOMEPAGE_GROUP:-Productivity}"
      - "homepage.name=${HULY_HOMEPAGE_NAME:-Huly}"
      - "homepage.icon=${HULY_HOMEPAGE_ICON:-si-linear}"
      - "homepage.href=${HULY_HOMEPAGE_URL:-}"
      - "homepage.description=${HULY_HOMEPAGE_DESCRIPTION:-All-in-one project management}"
      - "homepage.siteMonitor=${HULY_HOMEPAGE_SITEMONITOR:-http://front:8080}"

  fulltext:
    image: ${HULY_FULLTEXT_IMAGE:-docker.io/hardcoreeng/fulltext:v0.7.426}
    restart: ${HULY_RESTART:-unless-stopped}
    privileged: ${HULY_PRIVILEGED:-false}
    env_file:
      - ${HULY_FULLTEXT_ENV_FILE:-.env.example}
    environment:
      - TZ=${TZ:-America/Montreal}
      - SERVER_SECRET=${HULY_SECRET:-ChangeMe}
      - DB_URL=${HULY_CR_DB_URL:-postgres://huly:ChangeMe@postgresql:26257/huly}
      - FULLTEXT_DB_URL=${HULY_FULLTEXT_DB_URL:-http://elasticsearch:9200}
      - ELASTIC_INDEX_NAME=${HULY_ELASTIC_INDEX_NAME:-huly_storage_index}
      - STORAGE_CONFIG=${HULY_STORAGE_CONFIG:-minio|minio:9000?accessKey=ChangeMe&secretKey=ChangeMe&rootBucket=huly}
      - REKONI_URL=http://rekoni:4004
      - ACCOUNTS_URL=http://account:3000
      - STATS_URL=http://stats:4900
      - QUEUE_CONFIG=${HULY_QUEUE_CONFIG:-kafka:9092}
    networks:
      - default
    deploy:
      mode: ${HULY_FULLTEXT_DEPLOY_MODE:-replicated}
      replicas: ${HULY_FULLTEXT_DEPLOY_REPLICAS:-1}
      resources:
        limits:
          memory: ${HULY_FULLTEXT_MEMORY_LIMIT:-1G}
      placement:
        constraints:
          - ${HULY_FULLTEXT_PLACEMENT_CONSTRAINTS:-node.platform.os==linux}
      restart_policy:
        condition: ${HULY_FULLTEXT_RESTART_POLICY_CONDITION:-any}
        delay: ${HULY_FULLTEXT_RESTART_POLICY_DELAY:-5s}
        max_attempts: ${HULY_FULLTEXT_RESTART_POLICY_MAX_ATTEMPTS:-3}

  stream:
    image: ${HULY_STREAM_IMAGE:-docker.io/hardcoreeng/stream:v0.7.426}
    restart: ${HULY_RESTART:-unless-stopped}
    privileged: ${HULY_PRIVILEGED:-false}
    env_file:
      - ${HULY_STREAM_ENV_FILE:-.env.example}
    environment:
      - TZ=${TZ:-America/Montreal}
      - STREAM_SERVER_SECRET=${HULY_SECRET:-ChangeMe}
      - STREAM_ENDPOINT_URL=${HULY_STREAM_ENDPOINT_URL:-datalake://datalake:4030}
      - STREAM_INSECURE=${HULY_STREAM_INSECURE:-true}
      - STREAM_QUEUE_CONFIG=${HULY_QUEUE_CONFIG:-kafka:9092}
      - STREAM_REGION=${HULY_STREAM_REGION:-cockroach}
      - AWS_ACCESS_KEY_ID=${HULY_STREAM_ACCESS_KEY:-ChangeMe}
      - AWS_SECRET_ACCESS_KEY=${HULY_STREAM_SECRET_KEY:-ChangeMe}
    networks:
      - default
    deploy:
      mode: ${HULY_STREAM_DEPLOY_MODE:-replicated}
      replicas: ${HULY_STREAM_DEPLOY_REPLICAS:-1}
      resources:
        limits:
          memory: ${HULY_STREAM_MEMORY_LIMIT:-1G}
      placement:
        constraints:
          - ${HULY_STREAM_PLACEMENT_CONSTRAINTS:-node.platform.os==linux}
      restart_policy:
        condition: ${HULY_STREAM_RESTART_POLICY_CONDITION:-any}
        delay: ${HULY_STREAM_RESTART_POLICY_DELAY:-5s}
        max_attempts: ${HULY_STREAM_RESTART_POLICY_MAX_ATTEMPTS:-3}
      labels:
        - "traefik.enable=${HULY_TRAEFIK_LABELS_SWARM_ENABLE:-true}"
        - "traefik.http.services.${APP_NAME:-huly}-stream.loadbalancer.server.port=1080"
        - "traefik.http.routers.${APP_NAME:-huly}-stream.entrypoints=${HULY_ENTRYPOINTS:-web}"
        - "traefik.http.routers.${APP_NAME:-huly}-stream.rule=Host(`${HULY_DOMAIN:-huly.example.com}`) && PathPrefix(`/_stream`)"
        - "traefik.http.routers.${APP_NAME:-huly}-stream.service=${APP_NAME:-huly}-stream"
        - "traefik.http.routers.${APP_NAME:-huly}-stream.middlewares=${APP_NAME:-huly}-stream-strip"
        - "traefik.http.routers.${APP_NAME:-huly}-stream.priority=100"
        - "traefik.http.routers.${APP_NAME:-huly}-stream.tls=${HULY_TLS_ENABLED:-false}"
        - "traefik.http.routers.${APP_NAME:-huly}-stream.tls.certresolver=${HULY_TLS_CERTRESOLVER:-letsencrypt}"
        - "traefik.http.middlewares.${APP_NAME:-huly}-stream-strip.stripprefix.prefixes=/_stream"
        - "traefik.http.routers.${APP_NAME:-huly}-recording.entrypoints=${HULY_ENTRYPOINTS:-web}"
        - "traefik.http.routers.${APP_NAME:-huly}-recording.rule=Host(`${HULY_DOMAIN:-huly.example.com}`) && PathPrefix(`/recording`)"
        - "traefik.http.routers.${APP_NAME:-huly}-recording.service=${APP_NAME:-huly}-stream"
        - "traefik.http.routers.${APP_NAME:-huly}-recording.priority=100"
        - "traefik.http.routers.${APP_NAME:-huly}-recording.tls=${HULY_TLS_ENABLED:-false}"
        - "traefik.http.routers.${APP_NAME:-huly}-recording.tls.certresolver=${HULY_TLS_CERTRESOLVER:-letsencrypt}"
    labels:
      - "traefik.enable=${HULY_TRAEFIK_LABELS_DOCKER_ENABLE:-true}"
      - "traefik.http.services.${APP_NAME:-huly}-stream.loadbalancer.server.port=1080"
      - "traefik.http.routers.${APP_NAME:-huly}-stream.entrypoints=${HULY_ENTRYPOINTS:-web}"
      - "traefik.http.routers.${APP_NAME:-huly}-stream.rule=Host(`${HULY_DOMAIN:-huly.example.com}`) && PathPrefix(`/_stream`)"
      - "traefik.http.routers.${APP_NAME:-huly}-stream.service=${APP_NAME:-huly}-stream"
      - "traefik.http.routers.${APP_NAME:-huly}-stream.middlewares=${APP_NAME:-huly}-stream-strip"
      - "traefik.http.routers.${APP_NAME:-huly}-stream.priority=100"
      - "traefik.http.routers.${APP_NAME:-huly}-stream.tls=${HULY_TLS_ENABLED:-false}"
      - "traefik.http.routers.${APP_NAME:-huly}-stream.tls.certresolver=${HULY_TLS_CERTRESOLVER:-letsencrypt}"
      - "traefik.http.middlewares.${APP_NAME:-huly}-stream-strip.stripprefix.prefixes=/_stream"
      - "traefik.http.routers.${APP_NAME:-huly}-recording.entrypoints=${HULY_ENTRYPOINTS:-web}"
      - "traefik.http.routers.${APP_NAME:-huly}-recording.rule=Host(`${HULY_DOMAIN:-huly.example.com}`) && PathPrefix(`/recording`)"
      - "traefik.http.routers.${APP_NAME:-huly}-recording.service=${APP_NAME:-huly}-stream"
      - "traefik.http.routers.${APP_NAME:-huly}-recording.priority=100"
      - "traefik.http.routers.${APP_NAME:-huly}-recording.tls=${HULY_TLS_ENABLED:-false}"
      - "traefik.http.routers.${APP_NAME:-huly}-recording.tls.certresolver=${HULY_TLS_CERTRESOLVER:-letsencrypt}"

  datalake:
    image: ${HULY_DATALAKE_IMAGE:-docker.io/hardcoreeng/datalake:v0.7.426}
    restart: ${HULY_RESTART:-unless-stopped}
    privileged: ${HULY_PRIVILEGED:-false}
    env_file:
      - ${HULY_DATALAKE_ENV_FILE:-.env.example}
    environment:
      - TZ=${TZ:-America/Montreal}
      - PORT=${HULY_DATALAKE_PORT:-4030}
      - SECRET=${HULY_SECRET:-ChangeMe}
      - ACCOUNTS_URL=http://account:3000
      - STATS_URL=http://stats:4900
      - DB_URL=${HULY_CR_DB_URL:-postgres://huly:ChangeMe@postgresql:26257/huly}
      - BUCKETS=${HULY_DATALAKE_BUCKETS:-huly,eu|http://minio:9000?accessKey=ChangeMe&secretKey=ChangeMe}
      - REGION=${HULY_DATALAKE_REGION:-cockroach}
      - QUEUE_CONFIG=${HULY_QUEUE_CONFIG:-kafka:9092}
    networks:
      - default
    deploy:
      mode: ${HULY_DATALAKE_DEPLOY_MODE:-replicated}
      replicas: ${HULY_DATALAKE_DEPLOY_REPLICAS:-1}
      resources:
        limits:
          memory: ${HULY_DATALAKE_MEMORY_LIMIT:-512M}
      placement:
        constraints:
          - ${HULY_DATALAKE_PLACEMENT_CONSTRAINTS:-node.platform.os==linux}
      restart_policy:
        condition: ${HULY_DATALAKE_RESTART_POLICY_CONDITION:-any}
        delay: ${HULY_DATALAKE_RESTART_POLICY_DELAY:-5s}
        max_attempts: ${HULY_DATALAKE_RESTART_POLICY_MAX_ATTEMPTS:-3}
      labels:
        - "traefik.enable=${HULY_TRAEFIK_LABELS_SWARM_ENABLE:-true}"
        - "traefik.http.services.${APP_NAME:-huly}-datalake.loadbalancer.server.port=${HULY_DATALAKE_PORT:-4030}"
        - "traefik.http.routers.${APP_NAME:-huly}-datalake.entrypoints=${HULY_ENTRYPOINTS:-web}"
        - "traefik.http.routers.${APP_NAME:-huly}-datalake.rule=Host(`${HULY_DOMAIN:-huly.example.com}`) && PathPrefix(`/_datalake`)"
        - "traefik.http.routers.${APP_NAME:-huly}-datalake.service=${APP_NAME:-huly}-datalake"
        - "traefik.http.routers.${APP_NAME:-huly}-datalake.middlewares=${APP_NAME:-huly}-datalake-strip"
        - "traefik.http.routers.${APP_NAME:-huly}-datalake.priority=100"
        - "traefik.http.routers.${APP_NAME:-huly}-datalake.tls=${HULY_TLS_ENABLED:-false}"
        - "traefik.http.routers.${APP_NAME:-huly}-datalake.tls.certresolver=${HULY_TLS_CERTRESOLVER:-letsencrypt}"
        - "traefik.http.middlewares.${APP_NAME:-huly}-datalake-strip.stripprefix.prefixes=/_datalake"
    labels:
      - "traefik.enable=${HULY_TRAEFIK_LABELS_DOCKER_ENABLE:-true}"
      - "traefik.http.services.${APP_NAME:-huly}-datalake.loadbalancer.server.port=${HULY_DATALAKE_PORT:-4030}"
      - "traefik.http.routers.${APP_NAME:-huly}-datalake.entrypoints=${HULY_ENTRYPOINTS:-web}"
      - "traefik.http.routers.${APP_NAME:-huly}-datalake.rule=Host(`${HULY_DOMAIN:-huly.example.com}`) && PathPrefix(`/_datalake`)"
      - "traefik.http.routers.${APP_NAME:-huly}-datalake.service=${APP_NAME:-huly}-datalake"
      - "traefik.http.routers.${APP_NAME:-huly}-datalake.middlewares=${APP_NAME:-huly}-datalake-strip"
      - "traefik.http.routers.${APP_NAME:-huly}-datalake.priority=100"
      - "traefik.http.routers.${APP_NAME:-huly}-datalake.tls=${HULY_TLS_ENABLED:-false}"
      - "traefik.http.routers.${APP_NAME:-huly}-datalake.tls.certresolver=${HULY_TLS_CERTRESOLVER:-letsencrypt}"
      - "traefik.http.middlewares.${APP_NAME:-huly}-datalake-strip.stripprefix.prefixes=/_datalake"

  media:
    image: ${HULY_MEDIA_IMAGE:-docker.io/hardcoreeng/media:v0.7.426}
    restart: ${HULY_RESTART:-unless-stopped}
    privileged: ${HULY_PRIVILEGED:-false}
    env_file:
      - ${HULY_MEDIA_ENV_FILE:-.env.example}
    environment:
      - TZ=${TZ:-America/Montreal}
      - SECRET=${HULY_SECRET:-ChangeMe}
      - REGION=${HULY_MEDIA_REGION:-cockroach}
      - QUEUE_CONFIG=${HULY_QUEUE_CONFIG:-kafka:9092}
      - ACCOUNTS_URL=http://account:3000
    networks:
      - default
    deploy:
      mode: ${HULY_MEDIA_DEPLOY_MODE:-replicated}
      replicas: ${HULY_MEDIA_DEPLOY_REPLICAS:-1}
      resources:
        limits:
          memory: ${HULY_MEDIA_MEMORY_LIMIT:-512M}
      placement:
        constraints:
          - ${HULY_MEDIA_PLACEMENT_CONSTRAINTS:-node.platform.os==linux}
      restart_policy:
        condition: ${HULY_MEDIA_RESTART_POLICY_CONDITION:-any}
        delay: ${HULY_MEDIA_RESTART_POLICY_DELAY:-5s}
        max_attempts: ${HULY_MEDIA_RESTART_POLICY_MAX_ATTEMPTS:-3}


  mail:
    image: ${HULY_MAIL_IMAGE:-docker.io/hardcoreeng/mail:v0.7.426}
    restart: ${HULY_RESTART:-unless-stopped}
    privileged: ${HULY_PRIVILEGED:-false}
    env_file:
      - ${HULY_MAIL_ENV_FILE:-.env.example}
    environment:
      - TZ=${TZ:-America/Montreal}
      - PORT=${HULY_MAIL_PORT:-8097}
      - SOURCE=${HULY_MAIL_SOURCE:-noreply@huly.example.com}
      - SMTP_HOST=${HULY_SMTP_HOST:-}
      - SMTP_PORT=${HULY_SMTP_PORT:-587}
      - SMTP_USERNAME=${HULY_SMTP_USERNAME:-}
      - SMTP_PASSWORD=${HULY_SMTP_PASSWORD:-}
    networks:
      - default
    deploy:
      mode: ${HULY_MAIL_DEPLOY_MODE:-replicated}
      replicas: ${HULY_MAIL_DEPLOY_REPLICAS:-1}
      resources:
        limits:
          memory: ${HULY_MAIL_MEMORY_LIMIT:-256M}
      placement:
        constraints:
          - ${HULY_MAIL_PLACEMENT_CONSTRAINTS:-node.platform.os==linux}
      restart_policy:
        condition: ${HULY_MAIL_RESTART_POLICY_CONDITION:-any}
        delay: ${HULY_MAIL_RESTART_POLICY_DELAY:-5s}
        max_attempts: ${HULY_MAIL_RESTART_POLICY_MAX_ATTEMPTS:-3}

  stats:
    image: ${HULY_STATS_IMAGE:-docker.io/hardcoreeng/stats:v0.7.426}
    restart: ${HULY_RESTART:-unless-stopped}
    privileged: ${HULY_PRIVILEGED:-false}
    env_file:
      - ${HULY_STATS_ENV_FILE:-.env.example}
    environment:
      - TZ=${TZ:-America/Montreal}
      - PORT=${HULY_STATS_PORT:-4900}
      - SERVER_SECRET=${HULY_SECRET:-ChangeMe}
    networks:
      - default
    deploy:
      mode: ${HULY_STATS_DEPLOY_MODE:-replicated}
      replicas: ${HULY_STATS_DEPLOY_REPLICAS:-1}
      resources:
        limits:
          memory: ${HULY_STATS_MEMORY_LIMIT:-512M}
      placement:
        constraints:
          - ${HULY_STATS_PLACEMENT_CONSTRAINTS:-node.platform.os==linux}
      restart_policy:
        condition: ${HULY_STATS_RESTART_POLICY_CONDITION:-any}
        delay: ${HULY_STATS_RESTART_POLICY_DELAY:-5s}
        max_attempts: ${HULY_STATS_RESTART_POLICY_MAX_ATTEMPTS:-3}
      labels:
        - "traefik.enable=${HULY_TRAEFIK_LABELS_SWARM_ENABLE:-true}"
        - "traefik.http.services.${APP_NAME:-huly}-stats.loadbalancer.server.port=${HULY_STATS_PORT:-4900}"
        - "traefik.http.routers.${APP_NAME:-huly}-stats.entrypoints=${HULY_ENTRYPOINTS:-web}"
        - "traefik.http.routers.${APP_NAME:-huly}-stats.rule=Host(`${HULY_DOMAIN:-huly.example.com}`) && PathPrefix(`/_stats`)"
        - "traefik.http.routers.${APP_NAME:-huly}-stats.service=${APP_NAME:-huly}-stats"
        - "traefik.http.routers.${APP_NAME:-huly}-stats.middlewares=${APP_NAME:-huly}-stats-strip"
        - "traefik.http.routers.${APP_NAME:-huly}-stats.priority=100"
        - "traefik.http.routers.${APP_NAME:-huly}-stats.tls=${HULY_TLS_ENABLED:-false}"
        - "traefik.http.routers.${APP_NAME:-huly}-stats.tls.certresolver=${HULY_TLS_CERTRESOLVER:-letsencrypt}"
        - "traefik.http.middlewares.${APP_NAME:-huly}-stats-strip.stripprefix.prefixes=/_stats"
    labels:
      - "traefik.enable=${HULY_TRAEFIK_LABELS_DOCKER_ENABLE:-true}"
      - "traefik.http.services.${APP_NAME:-huly}-stats.loadbalancer.server.port=${HULY_STATS_PORT:-4900}"
      - "traefik.http.routers.${APP_NAME:-huly}-stats.entrypoints=${HULY_ENTRYPOINTS:-web}"
      - "traefik.http.routers.${APP_NAME:-huly}-stats.rule=Host(`${HULY_DOMAIN:-huly.example.com}`) && PathPrefix(`/_stats`)"
      - "traefik.http.routers.${APP_NAME:-huly}-stats.service=${APP_NAME:-huly}-stats"
      - "traefik.http.routers.${APP_NAME:-huly}-stats.middlewares=${APP_NAME:-huly}-stats-strip"
      - "traefik.http.routers.${APP_NAME:-huly}-stats.priority=100"
      - "traefik.http.routers.${APP_NAME:-huly}-stats.tls=${HULY_TLS_ENABLED:-false}"
      - "traefik.http.routers.${APP_NAME:-huly}-stats.tls.certresolver=${HULY_TLS_CERTRESOLVER:-letsencrypt}"
      - "traefik.http.middlewares.${APP_NAME:-huly}-stats-strip.stripprefix.prefixes=/_stats"

  kvs:
    image: ${HULY_KVS_IMAGE:-docker.io/hardcoreeng/hulykvs:v0.7.426}
    restart: ${HULY_RESTART:-unless-stopped}
    privileged: ${HULY_PRIVILEGED:-false}
    env_file:
      - ${HULY_KVS_ENV_FILE:-.env.example}
    environment:
      - TZ=${TZ:-America/Montreal}
      - HULY_DB_CONNECTION=${HULY_CR_DB_URL:-postgres://huly:ChangeMe@postgresql:26257/huly}
      - HULY_TOKEN_SECRET=${HULY_SECRET:-ChangeMe}
    networks:
      - default
    deploy:
      mode: ${HULY_KVS_DEPLOY_MODE:-replicated}
      replicas: ${HULY_KVS_DEPLOY_REPLICAS:-1}
      resources:
        limits:
          memory: ${HULY_KVS_MEMORY_LIMIT:-512M}
      placement:
        constraints:
          - ${HULY_KVS_PLACEMENT_CONSTRAINTS:-node.platform.os==linux}
      restart_policy:
        condition: ${HULY_KVS_RESTART_POLICY_CONDITION:-any}
        delay: ${HULY_KVS_RESTART_POLICY_DELAY:-5s}
        max_attempts: ${HULY_KVS_RESTART_POLICY_MAX_ATTEMPTS:-3}
