networks:
  default:
    name: ${DEFAULT_NETWORK_NAME:-huly-network}
    external: ${DEFAULT_NETWORK_EXTERNAL:-false}

services:
  workspace:
    image: ${HULY_WORKSPACE_IMAGE:-docker.io/hardcoreeng/workspace:v0.7.426}
    restart: ${HULY_RESTART:-unless-stopped}
    privileged: ${HULY_PRIVILEGED:-false}
    env_file:
      - ${HULY_WORKSPACE_ENV_FILE:-.env.example}
    environment:
      - TZ=${TZ:-America/Montreal}
      - SERVER_SECRET=${HULY_SECRET:-ChangeMe}
      - DB_URL=${HULY_CR_DB_URL:-postgres://huly:ChangeMe@postgresql:26257/huly}
      - TRANSACTOR_URL=ws://transactor:3333;${HULY_WS_SCHEME:-wss}://${HULY_DOMAIN:-huly.example.com}/_transactor
      - STORAGE_CONFIG=${HULY_STORAGE_CONFIG:-minio|minio:9000?accessKey=ChangeMe&secretKey=ChangeMe}
      - MODEL_ENABLED=${HULY_MODEL_ENABLED:-*}
      - ACCOUNTS_URL=http://account:3000
      - STATS_URL=http://stats:4900
      - QUEUE_CONFIG=${HULY_QUEUE_CONFIG:-kafka:9092}
      - ACCOUNTS_DB_URL=${HULY_CR_DB_URL:-postgres://huly:ChangeMe@postgresql:26257/huly}
      - INIT_REPO_DIR=${HULY_INIT_REPO_DIR:-}
    networks:
      - default
    deploy:
      mode: ${HULY_WORKSPACE_DEPLOY_MODE:-replicated}
      replicas: ${HULY_WORKSPACE_DEPLOY_REPLICAS:-1}
      resources:
        limits:
          memory: ${HULY_WORKSPACE_MEMORY_LIMIT:-1G}
      placement:
        constraints:
          - ${HULY_WORKSPACE_PLACEMENT_CONSTRAINTS:-node.platform.os==linux}
      restart_policy:
        condition: ${HULY_WORKSPACE_RESTART_POLICY_CONDITION:-any}
        delay: ${HULY_WORKSPACE_RESTART_POLICY_DELAY:-5s}
        max_attempts: ${HULY_WORKSPACE_RESTART_POLICY_MAX_ATTEMPTS:-3}
