networks:
  default:
    name: ${DEFAULT_NETWORK_NAME:-plane-network}
    external: ${DEFAULT_NETWORK_EXTERNAL:-false}

services:
  web:
    image: ${PLANE_WEB_IMAGE:-docker.io/makeplane/plane-frontend:stable}
    restart: ${PLANE_RESTART:-unless-stopped}
    privileged: ${PLANE_PRIVILEGED:-false}
    env_file:
      - ${PLANE_WEB_ENV_FILE:-.env.example}
    environment:
      - TZ=${TZ:-America/Montreal}
    networks:
      - default
    deploy:
      mode: ${PLANE_WEB_DEPLOY_MODE:-replicated}
      replicas: ${PLANE_WEB_DEPLOY_REPLICAS:-1}
      resources:
        limits:
          memory: ${PLANE_WEB_MEMORY_LIMIT:-1G}
      placement:
        constraints:
          - ${PLANE_WEB_PLACEMENT_CONSTRAINTS:-node.platform.os==linux}
      restart_policy:
        condition: ${PLANE_WEB_RESTART_POLICY_CONDITION:-any}
        delay: ${PLANE_WEB_RESTART_POLICY_DELAY:-5s}
        max_attempts: ${PLANE_WEB_RESTART_POLICY_MAX_ATTEMPTS:-3}
      labels:
        - "traefik.enable=${PLANE_TRAEFIK_LABELS_SWARM_ENABLE:-true}"
        - "traefik.http.services.${APP_NAME:-plane}-web.loadbalancer.server.port=${PLANE_WEB_PORT:-3000}"
        - "traefik.http.routers.${APP_NAME:-plane}-web.entrypoints=${PLANE_ENTRYPOINTS:-web}"
        - "traefik.http.routers.${APP_NAME:-plane}-web.rule=Host(`${PLANE_DOMAIN:-plane.example.com}`)"
        - "traefik.http.routers.${APP_NAME:-plane}-web.service=${APP_NAME:-plane}-web"
        - "traefik.http.routers.${APP_NAME:-plane}-web.middlewares=${PLANE_MIDDLEWARES:-}"
        - "traefik.http.routers.${APP_NAME:-plane}-web.tls=${PLANE_TLS_ENABLED:-false}"
        - "traefik.http.routers.${APP_NAME:-plane}-web.tls.certresolver=${PLANE_TLS_CERTRESOLVER:-letsencrypt}"
        - "homepage.group=${PLANE_HOMEPAGE_GROUP:-Productivity}"
        - "homepage.name=${PLANE_HOMEPAGE_NAME:-Plane}"
        - "homepage.icon=${PLANE_HOMEPAGE_ICON:-plane.png}"
        - "homepage.href=${PLANE_HOMEPAGE_URL:-}"
        - "homepage.description=${PLANE_HOMEPAGE_DESCRIPTION:-Project management}"
        - "homepage.siteMonitor=${PLANE_HOMEPAGE_SITEMONITOR:-http://web:3000}"
    labels:
      - "traefik.enable=${PLANE_TRAEFIK_LABELS_DOCKER_ENABLE:-true}"
      - "traefik.http.services.${APP_NAME:-plane}-web.loadbalancer.server.port=${PLANE_WEB_PORT:-3000}"
      - "traefik.http.routers.${APP_NAME:-plane}-web.entrypoints=${PLANE_ENTRYPOINTS:-web}"
      - "traefik.http.routers.${APP_NAME:-plane}-web.rule=Host(`${PLANE_DOMAIN:-plane.example.com}`)"
      - "traefik.http.routers.${APP_NAME:-plane}-web.service=${APP_NAME:-plane}-web"
      - "traefik.http.routers.${APP_NAME:-plane}-web.middlewares=${PLANE_MIDDLEWARES:-}"
      - "traefik.http.routers.${APP_NAME:-plane}-web.tls=${PLANE_TLS_ENABLED:-false}"
      - "traefik.http.routers.${APP_NAME:-plane}-web.tls.certresolver=${PLANE_TLS_CERTRESOLVER:-letsencrypt}"
      - "homepage.group=${PLANE_HOMEPAGE_GROUP:-Productivity}"
      - "homepage.name=${PLANE_HOMEPAGE_NAME:-Plane}"
      - "homepage.icon=${PLANE_HOMEPAGE_ICON:-plane.png}"
      - "homepage.href=${PLANE_HOMEPAGE_URL:-}"
      - "homepage.description=${PLANE_HOMEPAGE_DESCRIPTION:-Project management}"
      - "homepage.siteMonitor=${PLANE_HOMEPAGE_SITEMONITOR:-http://web:3000}"

  space:
    image: ${PLANE_SPACE_IMAGE:-docker.io/makeplane/plane-space:stable}
    restart: ${PLANE_RESTART:-unless-stopped}
    privileged: ${PLANE_PRIVILEGED:-false}
    env_file:
      - ${PLANE_SPACE_ENV_FILE:-.env.example}
    environment:
      - TZ=${TZ:-America/Montreal}
    networks:
      - default
    deploy:
      mode: ${PLANE_SPACE_DEPLOY_MODE:-replicated}
      replicas: ${PLANE_SPACE_DEPLOY_REPLICAS:-1}
      resources:
        limits:
          memory: ${PLANE_SPACE_MEMORY_LIMIT:-1G}
      placement:
        constraints:
          - ${PLANE_SPACE_PLACEMENT_CONSTRAINTS:-node.platform.os==linux}
      restart_policy:
        condition: ${PLANE_SPACE_RESTART_POLICY_CONDITION:-any}
        delay: ${PLANE_SPACE_RESTART_POLICY_DELAY:-5s}
        max_attempts: ${PLANE_SPACE_RESTART_POLICY_MAX_ATTEMPTS:-3}
      labels:
        - "traefik.enable=${PLANE_TRAEFIK_LABELS_SWARM_ENABLE:-true}"
        - "traefik.http.services.${APP_NAME:-plane}-space.loadbalancer.server.port=${PLANE_SPACE_PORT:-3000}"
        - "traefik.http.routers.${APP_NAME:-plane}-space.entrypoints=${PLANE_ENTRYPOINTS:-web}"
        - "traefik.http.routers.${APP_NAME:-plane}-space.rule=Host(`${PLANE_DOMAIN:-plane.example.com}`) && (Path(`/spaces`) || PathPrefix(`/spaces/`))"
        - "traefik.http.routers.${APP_NAME:-plane}-space.service=${APP_NAME:-plane}-space"
        - "traefik.http.routers.${APP_NAME:-plane}-space.middlewares=${PLANE_MIDDLEWARES:-}"
        - "traefik.http.routers.${APP_NAME:-plane}-space.tls=${PLANE_TLS_ENABLED:-false}"
        - "traefik.http.routers.${APP_NAME:-plane}-space.tls.certresolver=${PLANE_TLS_CERTRESOLVER:-letsencrypt}"
    labels:
      - "traefik.enable=${PLANE_TRAEFIK_LABELS_DOCKER_ENABLE:-true}"
      - "traefik.http.services.${APP_NAME:-plane}-space.loadbalancer.server.port=${PLANE_SPACE_PORT:-3000}"
      - "traefik.http.routers.${APP_NAME:-plane}-space.entrypoints=${PLANE_ENTRYPOINTS:-web}"
      - "traefik.http.routers.${APP_NAME:-plane}-space.rule=Host(`${PLANE_DOMAIN:-plane.example.com}`) && (Path(`/spaces`) || PathPrefix(`/spaces/`))"
      - "traefik.http.routers.${APP_NAME:-plane}-space.service=${APP_NAME:-plane}-space"
      - "traefik.http.routers.${APP_NAME:-plane}-space.middlewares=${PLANE_MIDDLEWARES:-}"
      - "traefik.http.routers.${APP_NAME:-plane}-space.tls=${PLANE_TLS_ENABLED:-false}"
      - "traefik.http.routers.${APP_NAME:-plane}-space.tls.certresolver=${PLANE_TLS_CERTRESOLVER:-letsencrypt}"

  admin:
    image: ${PLANE_ADMIN_IMAGE:-docker.io/makeplane/plane-admin:stable}
    restart: ${PLANE_RESTART:-unless-stopped}
    privileged: ${PLANE_PRIVILEGED:-false}
    env_file:
      - ${PLANE_ADMIN_ENV_FILE:-.env.example}
    environment:
      - TZ=${TZ:-America/Montreal}
    networks:
      - default
    deploy:
      mode: ${PLANE_ADMIN_DEPLOY_MODE:-replicated}
      replicas: ${PLANE_ADMIN_DEPLOY_REPLICAS:-1}
      resources:
        limits:
          memory: ${PLANE_ADMIN_MEMORY_LIMIT:-1G}
      placement:
        constraints:
          - ${PLANE_ADMIN_PLACEMENT_CONSTRAINTS:-node.platform.os==linux}
      restart_policy:
        condition: ${PLANE_ADMIN_RESTART_POLICY_CONDITION:-any}
        delay: ${PLANE_ADMIN_RESTART_POLICY_DELAY:-5s}
        max_attempts: ${PLANE_ADMIN_RESTART_POLICY_MAX_ATTEMPTS:-3}
      labels:
        - "traefik.enable=${PLANE_TRAEFIK_LABELS_SWARM_ENABLE:-true}"
        - "traefik.http.services.${APP_NAME:-plane}-admin.loadbalancer.server.port=${PLANE_ADMIN_PORT:-3000}"
        - "traefik.http.routers.${APP_NAME:-plane}-admin.entrypoints=${PLANE_ENTRYPOINTS:-web}"
        - "traefik.http.routers.${APP_NAME:-plane}-admin.rule=Host(`${PLANE_DOMAIN:-plane.example.com}`) && (Path(`/god-mode`) || PathPrefix(`/god-mode/`))"
        - "traefik.http.routers.${APP_NAME:-plane}-admin.service=${APP_NAME:-plane}-admin"
        - "traefik.http.routers.${APP_NAME:-plane}-admin.middlewares=${PLANE_MIDDLEWARES:-}"
        - "traefik.http.routers.${APP_NAME:-plane}-admin.tls=${PLANE_TLS_ENABLED:-false}"
        - "traefik.http.routers.${APP_NAME:-plane}-admin.tls.certresolver=${PLANE_TLS_CERTRESOLVER:-letsencrypt}"
    labels:
      - "traefik.enable=${PLANE_TRAEFIK_LABELS_DOCKER_ENABLE:-true}"
      - "traefik.http.services.${APP_NAME:-plane}-admin.loadbalancer.server.port=${PLANE_ADMIN_PORT:-3000}"
      - "traefik.http.routers.${APP_NAME:-plane}-admin.entrypoints=${PLANE_ENTRYPOINTS:-web}"
      - "traefik.http.routers.${APP_NAME:-plane}-admin.rule=Host(`${PLANE_DOMAIN:-plane.example.com}`) && (Path(`/god-mode`) || PathPrefix(`/god-mode/`))"
      - "traefik.http.routers.${APP_NAME:-plane}-admin.service=${APP_NAME:-plane}-admin"
      - "traefik.http.routers.${APP_NAME:-plane}-admin.middlewares=${PLANE_MIDDLEWARES:-}"
      - "traefik.http.routers.${APP_NAME:-plane}-admin.tls=${PLANE_TLS_ENABLED:-false}"
      - "traefik.http.routers.${APP_NAME:-plane}-admin.tls.certresolver=${PLANE_TLS_CERTRESOLVER:-letsencrypt}"

  live:
    image: ${PLANE_LIVE_IMAGE:-docker.io/makeplane/plane-live:stable}
    restart: ${PLANE_RESTART:-unless-stopped}
    privileged: ${PLANE_PRIVILEGED:-false}
    env_file:
      - ${PLANE_LIVE_ENV_FILE:-.env.example}
    environment:
      - TZ=${TZ:-America/Montreal}
      - API_BASE_URL=${PLANE_API_BASE_URL:-http://api:8000}
      - LIVE_SERVER_SECRET_KEY=${PLANE_LIVE_SERVER_SECRET_KEY:-ChangeMe}
      - REDIS_HOST=${PLANE_REDIS_HOST:-redis}
      - REDIS_PORT=${PLANE_REDIS_PORT:-6379}
      - REDIS_URL=${PLANE_REDIS_URL:-redis://redis:6379/}
    networks:
      - default
    deploy:
      mode: ${PLANE_LIVE_DEPLOY_MODE:-replicated}
      replicas: ${PLANE_LIVE_DEPLOY_REPLICAS:-1}
      resources:
        limits:
          memory: ${PLANE_LIVE_MEMORY_LIMIT:-1G}
      placement:
        constraints:
          - ${PLANE_LIVE_PLACEMENT_CONSTRAINTS:-node.platform.os==linux}
      restart_policy:
        condition: ${PLANE_LIVE_RESTART_POLICY_CONDITION:-any}
        delay: ${PLANE_LIVE_RESTART_POLICY_DELAY:-5s}
        max_attempts: ${PLANE_LIVE_RESTART_POLICY_MAX_ATTEMPTS:-3}
      labels:
        - "traefik.enable=${PLANE_TRAEFIK_LABELS_SWARM_ENABLE:-true}"
        - "traefik.http.services.${APP_NAME:-plane}-live.loadbalancer.server.port=${PLANE_LIVE_PORT:-3000}"
        - "traefik.http.routers.${APP_NAME:-plane}-live.entrypoints=${PLANE_ENTRYPOINTS:-web}"
        - "traefik.http.routers.${APP_NAME:-plane}-live.rule=Host(`${PLANE_DOMAIN:-plane.example.com}`) && (Path(`/live`) || PathPrefix(`/live/`))"
        - "traefik.http.routers.${APP_NAME:-plane}-live.service=${APP_NAME:-plane}-live"
        - "traefik.http.routers.${APP_NAME:-plane}-live.middlewares=${PLANE_MIDDLEWARES:-}"
        - "traefik.http.routers.${APP_NAME:-plane}-live.tls=${PLANE_TLS_ENABLED:-false}"
        - "traefik.http.routers.${APP_NAME:-plane}-live.tls.certresolver=${PLANE_TLS_CERTRESOLVER:-letsencrypt}"
    labels:
      - "traefik.enable=${PLANE_TRAEFIK_LABELS_DOCKER_ENABLE:-true}"
      - "traefik.http.services.${APP_NAME:-plane}-live.loadbalancer.server.port=${PLANE_LIVE_PORT:-3000}"
      - "traefik.http.routers.${APP_NAME:-plane}-live.entrypoints=${PLANE_ENTRYPOINTS:-web}"
      - "traefik.http.routers.${APP_NAME:-plane}-live.rule=Host(`${PLANE_DOMAIN:-plane.example.com}`) && (Path(`/live`) || PathPrefix(`/live/`))"
      - "traefik.http.routers.${APP_NAME:-plane}-live.service=${APP_NAME:-plane}-live"
      - "traefik.http.routers.${APP_NAME:-plane}-live.middlewares=${PLANE_MIDDLEWARES:-}"
      - "traefik.http.routers.${APP_NAME:-plane}-live.tls=${PLANE_TLS_ENABLED:-false}"
      - "traefik.http.routers.${APP_NAME:-plane}-live.tls.certresolver=${PLANE_TLS_CERTRESOLVER:-letsencrypt}"

  api:
    image: ${PLANE_API_IMAGE:-docker.io/makeplane/plane-backend:stable}
    command: ./bin/docker-entrypoint-api.sh
    restart: ${PLANE_RESTART:-unless-stopped}
    privileged: ${PLANE_PRIVILEGED:-false}
    env_file:
      - ${PLANE_API_ENV_FILE:-.env.example}
    environment:
      - TZ=${TZ:-America/Montreal}
      - WEB_URL=${PLANE_APP_URL:-http://plane.example.com}
      - DEBUG=${PLANE_DEBUG:-0}
      - CORS_ALLOWED_ORIGINS=${PLANE_CORS_ALLOWED_ORIGINS:-http://plane.example.com}
      - GUNICORN_WORKERS=${PLANE_GUNICORN_WORKERS:-1}
      - USE_MINIO=${PLANE_USE_MINIO:-0}
      - DATABASE_URL=${PLANE_DATABASE_URL:-postgresql://plane:ChangeMe@postgres:5432/plane}
      - SECRET_KEY=${PLANE_SECRET_KEY:-ChangeMe}
      - AMQP_URL=${PLANE_AMQP_URL:-amqp://plane:ChangeMe@rabbitmq:5672/plane}
      - API_KEY_RATE_LIMIT=${PLANE_API_KEY_RATE_LIMIT:-60/minute}
      - AUTHENTICATION_RATE_LIMIT=${PLANE_AUTHENTICATION_RATE_LIMIT:-10/minute}
      - MINIO_ENDPOINT_SSL=${PLANE_MINIO_ENDPOINT_SSL:-0}
      - LIVE_SERVER_SECRET_KEY=${PLANE_LIVE_SERVER_SECRET_KEY:-ChangeMe}
      - WEBHOOK_ALLOWED_IPS=${PLANE_WEBHOOK_ALLOWED_IPS:-}
      - WEBHOOK_ALLOWED_HOSTS=${PLANE_WEBHOOK_ALLOWED_HOSTS:-}
      - PGHOST=${PLANE_PGHOST:-postgres}
      - PGDATABASE=${PLANE_PGDATABASE:-plane}
      - POSTGRES_USER=${PLANE_POSTGRES_USER:-plane}
      - POSTGRES_PASSWORD=${PLANE_POSTGRES_PASSWORD:-ChangeMe}
      - POSTGRES_DB=${PLANE_POSTGRES_DB:-plane}
      - POSTGRES_PORT=${PLANE_POSTGRES_PORT:-5432}
      - REDIS_HOST=${PLANE_REDIS_HOST:-redis}
      - REDIS_PORT=${PLANE_REDIS_PORT:-6379}
      - REDIS_URL=${PLANE_REDIS_URL:-redis://redis:6379/}
      - AWS_REGION=${PLANE_AWS_REGION:-}
      - AWS_ACCESS_KEY_ID=${PLANE_AWS_ACCESS_KEY_ID:-access-key}
      - AWS_SECRET_ACCESS_KEY=${PLANE_AWS_SECRET_ACCESS_KEY:-ChangeMe}
      - AWS_S3_ENDPOINT_URL=${PLANE_S3_ENDPOINT_URL:-http://minio:9000}
      - AWS_S3_BUCKET_NAME=${PLANE_S3_BUCKET_NAME:-uploads}
      - FILE_SIZE_LIMIT=${PLANE_FILE_SIZE_LIMIT:-5242880}
      - APP_DOMAIN=${PLANE_DOMAIN:-plane.example.com}
    networks:
      - default
    deploy:
      mode: ${PLANE_API_DEPLOY_MODE:-replicated}
      replicas: ${PLANE_API_DEPLOY_REPLICAS:-1}
      resources:
        limits:
          memory: ${PLANE_API_MEMORY_LIMIT:-1G}
      placement:
        constraints:
          - ${PLANE_API_PLACEMENT_CONSTRAINTS:-node.platform.os==linux}
      restart_policy:
        condition: ${PLANE_API_RESTART_POLICY_CONDITION:-any}
        delay: ${PLANE_API_RESTART_POLICY_DELAY:-5s}
        max_attempts: ${PLANE_API_RESTART_POLICY_MAX_ATTEMPTS:-3}
      labels:
        - "traefik.enable=${PLANE_TRAEFIK_LABELS_SWARM_ENABLE:-true}"
        - "traefik.http.services.${APP_NAME:-plane}-api.loadbalancer.server.port=${PLANE_API_PORT:-8000}"
        - "traefik.http.routers.${APP_NAME:-plane}-api.entrypoints=${PLANE_ENTRYPOINTS:-web}"
        - "traefik.http.routers.${APP_NAME:-plane}-api.rule=Host(`${PLANE_DOMAIN:-plane.example.com}`) && (Path(`/api`) || PathPrefix(`/api/`) || Path(`/auth`) || PathPrefix(`/auth/`) || Path(`/static`) || PathPrefix(`/static/`))"
        - "traefik.http.routers.${APP_NAME:-plane}-api.service=${APP_NAME:-plane}-api"
        - "traefik.http.routers.${APP_NAME:-plane}-api.middlewares=${PLANE_MIDDLEWARES:-}"
        - "traefik.http.routers.${APP_NAME:-plane}-api.tls=${PLANE_TLS_ENABLED:-false}"
        - "traefik.http.routers.${APP_NAME:-plane}-api.tls.certresolver=${PLANE_TLS_CERTRESOLVER:-letsencrypt}"
    labels:
      - "traefik.enable=${PLANE_TRAEFIK_LABELS_DOCKER_ENABLE:-true}"
      - "traefik.http.services.${APP_NAME:-plane}-api.loadbalancer.server.port=${PLANE_API_PORT:-8000}"
      - "traefik.http.routers.${APP_NAME:-plane}-api.entrypoints=${PLANE_ENTRYPOINTS:-web}"
      - "traefik.http.routers.${APP_NAME:-plane}-api.rule=Host(`${PLANE_DOMAIN:-plane.example.com}`) && (Path(`/api`) || PathPrefix(`/api/`) || Path(`/auth`) || PathPrefix(`/auth/`) || Path(`/static`) || PathPrefix(`/static/`))"
      - "traefik.http.routers.${APP_NAME:-plane}-api.service=${APP_NAME:-plane}-api"
      - "traefik.http.routers.${APP_NAME:-plane}-api.middlewares=${PLANE_MIDDLEWARES:-}"
      - "traefik.http.routers.${APP_NAME:-plane}-api.tls=${PLANE_TLS_ENABLED:-false}"
      - "traefik.http.routers.${APP_NAME:-plane}-api.tls.certresolver=${PLANE_TLS_CERTRESOLVER:-letsencrypt}"

  worker:
    image: ${PLANE_WORKER_IMAGE:-docker.io/makeplane/plane-backend:stable}
    command: ./bin/docker-entrypoint-worker.sh
    restart: ${PLANE_RESTART:-unless-stopped}
    privileged: ${PLANE_PRIVILEGED:-false}
    env_file:
      - ${PLANE_WORKER_ENV_FILE:-.env.example}
    environment:
      - TZ=${TZ:-America/Montreal}
      - WEB_URL=${PLANE_APP_URL:-http://plane.example.com}
      - DEBUG=${PLANE_DEBUG:-0}
      - CORS_ALLOWED_ORIGINS=${PLANE_CORS_ALLOWED_ORIGINS:-http://plane.example.com}
      - GUNICORN_WORKERS=${PLANE_GUNICORN_WORKERS:-1}
      - USE_MINIO=${PLANE_USE_MINIO:-0}
      - DATABASE_URL=${PLANE_DATABASE_URL:-postgresql://plane:ChangeMe@postgres:5432/plane}
      - SECRET_KEY=${PLANE_SECRET_KEY:-ChangeMe}
      - AMQP_URL=${PLANE_AMQP_URL:-amqp://plane:ChangeMe@rabbitmq:5672/plane}
      - API_KEY_RATE_LIMIT=${PLANE_API_KEY_RATE_LIMIT:-60/minute}
      - AUTHENTICATION_RATE_LIMIT=${PLANE_AUTHENTICATION_RATE_LIMIT:-10/minute}
      - MINIO_ENDPOINT_SSL=${PLANE_MINIO_ENDPOINT_SSL:-0}
      - LIVE_SERVER_SECRET_KEY=${PLANE_LIVE_SERVER_SECRET_KEY:-ChangeMe}
      - WEBHOOK_ALLOWED_IPS=${PLANE_WEBHOOK_ALLOWED_IPS:-}
      - WEBHOOK_ALLOWED_HOSTS=${PLANE_WEBHOOK_ALLOWED_HOSTS:-}
      - PGHOST=${PLANE_PGHOST:-postgres}
      - PGDATABASE=${PLANE_PGDATABASE:-plane}
      - POSTGRES_USER=${PLANE_POSTGRES_USER:-plane}
      - POSTGRES_PASSWORD=${PLANE_POSTGRES_PASSWORD:-ChangeMe}
      - POSTGRES_DB=${PLANE_POSTGRES_DB:-plane}
      - POSTGRES_PORT=${PLANE_POSTGRES_PORT:-5432}
      - REDIS_HOST=${PLANE_REDIS_HOST:-redis}
      - REDIS_PORT=${PLANE_REDIS_PORT:-6379}
      - REDIS_URL=${PLANE_REDIS_URL:-redis://redis:6379/}
      - AWS_REGION=${PLANE_AWS_REGION:-}
      - AWS_ACCESS_KEY_ID=${PLANE_AWS_ACCESS_KEY_ID:-access-key}
      - AWS_SECRET_ACCESS_KEY=${PLANE_AWS_SECRET_ACCESS_KEY:-ChangeMe}
      - AWS_S3_ENDPOINT_URL=${PLANE_S3_ENDPOINT_URL:-http://minio:9000}
      - AWS_S3_BUCKET_NAME=${PLANE_S3_BUCKET_NAME:-uploads}
      - FILE_SIZE_LIMIT=${PLANE_FILE_SIZE_LIMIT:-5242880}
      - APP_DOMAIN=${PLANE_DOMAIN:-plane.example.com}
    networks:
      - default
    deploy:
      mode: ${PLANE_WORKER_DEPLOY_MODE:-replicated}
      replicas: ${PLANE_WORKER_DEPLOY_REPLICAS:-1}
      resources:
        limits:
          memory: ${PLANE_WORKER_MEMORY_LIMIT:-1G}
      placement:
        constraints:
          - ${PLANE_WORKER_PLACEMENT_CONSTRAINTS:-node.platform.os==linux}
      restart_policy:
        condition: ${PLANE_WORKER_RESTART_POLICY_CONDITION:-any}
        delay: ${PLANE_WORKER_RESTART_POLICY_DELAY:-5s}
        max_attempts: ${PLANE_WORKER_RESTART_POLICY_MAX_ATTEMPTS:-3}

  beat-worker:
    image: ${PLANE_BEAT_WORKER_IMAGE:-docker.io/makeplane/plane-backend:stable}
    command: ./bin/docker-entrypoint-beat.sh
    restart: ${PLANE_RESTART:-unless-stopped}
    privileged: ${PLANE_PRIVILEGED:-false}
    env_file:
      - ${PLANE_BEAT_WORKER_ENV_FILE:-.env.example}
    environment:
      - TZ=${TZ:-America/Montreal}
      - WEB_URL=${PLANE_APP_URL:-http://plane.example.com}
      - DEBUG=${PLANE_DEBUG:-0}
      - CORS_ALLOWED_ORIGINS=${PLANE_CORS_ALLOWED_ORIGINS:-http://plane.example.com}
      - GUNICORN_WORKERS=${PLANE_GUNICORN_WORKERS:-1}
      - USE_MINIO=${PLANE_USE_MINIO:-0}
      - DATABASE_URL=${PLANE_DATABASE_URL:-postgresql://plane:ChangeMe@postgres:5432/plane}
      - SECRET_KEY=${PLANE_SECRET_KEY:-ChangeMe}
      - AMQP_URL=${PLANE_AMQP_URL:-amqp://plane:ChangeMe@rabbitmq:5672/plane}
      - API_KEY_RATE_LIMIT=${PLANE_API_KEY_RATE_LIMIT:-60/minute}
      - AUTHENTICATION_RATE_LIMIT=${PLANE_AUTHENTICATION_RATE_LIMIT:-10/minute}
      - MINIO_ENDPOINT_SSL=${PLANE_MINIO_ENDPOINT_SSL:-0}
      - LIVE_SERVER_SECRET_KEY=${PLANE_LIVE_SERVER_SECRET_KEY:-ChangeMe}
      - WEBHOOK_ALLOWED_IPS=${PLANE_WEBHOOK_ALLOWED_IPS:-}
      - WEBHOOK_ALLOWED_HOSTS=${PLANE_WEBHOOK_ALLOWED_HOSTS:-}
      - PGHOST=${PLANE_PGHOST:-postgres}
      - PGDATABASE=${PLANE_PGDATABASE:-plane}
      - POSTGRES_USER=${PLANE_POSTGRES_USER:-plane}
      - POSTGRES_PASSWORD=${PLANE_POSTGRES_PASSWORD:-ChangeMe}
      - POSTGRES_DB=${PLANE_POSTGRES_DB:-plane}
      - POSTGRES_PORT=${PLANE_POSTGRES_PORT:-5432}
      - REDIS_HOST=${PLANE_REDIS_HOST:-redis}
      - REDIS_PORT=${PLANE_REDIS_PORT:-6379}
      - REDIS_URL=${PLANE_REDIS_URL:-redis://redis:6379/}
      - AWS_REGION=${PLANE_AWS_REGION:-}
      - AWS_ACCESS_KEY_ID=${PLANE_AWS_ACCESS_KEY_ID:-access-key}
      - AWS_SECRET_ACCESS_KEY=${PLANE_AWS_SECRET_ACCESS_KEY:-ChangeMe}
      - AWS_S3_ENDPOINT_URL=${PLANE_S3_ENDPOINT_URL:-http://minio:9000}
      - AWS_S3_BUCKET_NAME=${PLANE_S3_BUCKET_NAME:-uploads}
      - FILE_SIZE_LIMIT=${PLANE_FILE_SIZE_LIMIT:-5242880}
      - APP_DOMAIN=${PLANE_DOMAIN:-plane.example.com}
    networks:
      - default
    deploy:
      mode: ${PLANE_BEAT_WORKER_DEPLOY_MODE:-replicated}
      replicas: ${PLANE_BEAT_WORKER_DEPLOY_REPLICAS:-1}
      resources:
        limits:
          memory: ${PLANE_BEAT_WORKER_MEMORY_LIMIT:-1G}
      placement:
        constraints:
          - ${PLANE_BEAT_WORKER_PLACEMENT_CONSTRAINTS:-node.platform.os==linux}
      restart_policy:
        condition: ${PLANE_BEAT_WORKER_RESTART_POLICY_CONDITION:-any}
        delay: ${PLANE_BEAT_WORKER_RESTART_POLICY_DELAY:-5s}
        max_attempts: ${PLANE_BEAT_WORKER_RESTART_POLICY_MAX_ATTEMPTS:-3}

  migrator:
    image: ${PLANE_MIGRATOR_IMAGE:-docker.io/makeplane/plane-backend:stable}
    command: ./bin/docker-entrypoint-migrator.sh
    restart: ${PLANE_RESTART:-unless-stopped}
    privileged: ${PLANE_PRIVILEGED:-false}
    env_file:
      - ${PLANE_MIGRATOR_ENV_FILE:-.env.example}
    environment:
      - TZ=${TZ:-America/Montreal}
      - WEB_URL=${PLANE_APP_URL:-http://plane.example.com}
      - DEBUG=${PLANE_DEBUG:-0}
      - CORS_ALLOWED_ORIGINS=${PLANE_CORS_ALLOWED_ORIGINS:-http://plane.example.com}
      - GUNICORN_WORKERS=${PLANE_GUNICORN_WORKERS:-1}
      - USE_MINIO=${PLANE_USE_MINIO:-0}
      - DATABASE_URL=${PLANE_DATABASE_URL:-postgresql://plane:ChangeMe@postgres:5432/plane}
      - SECRET_KEY=${PLANE_SECRET_KEY:-ChangeMe}
      - AMQP_URL=${PLANE_AMQP_URL:-amqp://plane:ChangeMe@rabbitmq:5672/plane}
      - API_KEY_RATE_LIMIT=${PLANE_API_KEY_RATE_LIMIT:-60/minute}
      - AUTHENTICATION_RATE_LIMIT=${PLANE_AUTHENTICATION_RATE_LIMIT:-10/minute}
      - MINIO_ENDPOINT_SSL=${PLANE_MINIO_ENDPOINT_SSL:-0}
      - LIVE_SERVER_SECRET_KEY=${PLANE_LIVE_SERVER_SECRET_KEY:-ChangeMe}
      - WEBHOOK_ALLOWED_IPS=${PLANE_WEBHOOK_ALLOWED_IPS:-}
      - WEBHOOK_ALLOWED_HOSTS=${PLANE_WEBHOOK_ALLOWED_HOSTS:-}
      - PGHOST=${PLANE_PGHOST:-postgres}
      - PGDATABASE=${PLANE_PGDATABASE:-plane}
      - POSTGRES_USER=${PLANE_POSTGRES_USER:-plane}
      - POSTGRES_PASSWORD=${PLANE_POSTGRES_PASSWORD:-ChangeMe}
      - POSTGRES_DB=${PLANE_POSTGRES_DB:-plane}
      - POSTGRES_PORT=${PLANE_POSTGRES_PORT:-5432}
      - REDIS_HOST=${PLANE_REDIS_HOST:-redis}
      - REDIS_PORT=${PLANE_REDIS_PORT:-6379}
      - REDIS_URL=${PLANE_REDIS_URL:-redis://redis:6379/}
      - AWS_REGION=${PLANE_AWS_REGION:-}
      - AWS_ACCESS_KEY_ID=${PLANE_AWS_ACCESS_KEY_ID:-access-key}
      - AWS_SECRET_ACCESS_KEY=${PLANE_AWS_SECRET_ACCESS_KEY:-ChangeMe}
      - AWS_S3_ENDPOINT_URL=${PLANE_S3_ENDPOINT_URL:-http://minio:9000}
      - AWS_S3_BUCKET_NAME=${PLANE_S3_BUCKET_NAME:-uploads}
      - FILE_SIZE_LIMIT=${PLANE_FILE_SIZE_LIMIT:-5242880}
      - APP_DOMAIN=${PLANE_DOMAIN:-plane.example.com}
    networks:
      - default
    deploy:
      mode: ${PLANE_MIGRATOR_DEPLOY_MODE:-replicated}
      replicas: ${PLANE_MIGRATOR_DEPLOY_REPLICAS:-1}
      resources:
        limits:
          memory: ${PLANE_MIGRATOR_MEMORY_LIMIT:-1G}
      placement:
        constraints:
          - ${PLANE_MIGRATOR_PLACEMENT_CONSTRAINTS:-node.platform.os==linux}
      restart_policy:
        condition: ${PLANE_MIGRATOR_RESTART_POLICY_CONDITION:-on-failure}
        delay: ${PLANE_MIGRATOR_RESTART_POLICY_DELAY:-5s}
        max_attempts: ${PLANE_MIGRATOR_RESTART_POLICY_MAX_ATTEMPTS:-3}
