networks:
  default:
    name: ${DEFAULT_NETWORK:-dokploy-network}
    external: ${DEFAULT_NETWORK_EXTERNAL:-true}
services:
  smtp-relay:
    image: ${SMTP_RELAY_IMAGE:-namshi/smtp:latest}
    x-pull-policy: ${SMTP_RELAY_PULL_POLICY:-always}
    restart: ${SMTP_RELAY_RESTART:-unless-stopped}
    environment:
      TZ: ${TZ}
      MAILNAME: ${SMTP_RELAY_MAILNAME:-smtp.example.com}
      RELAY_NETWORKS: ${SMTP_RELAY_NETWORKS:-:192.168.31.0/16:10.16.0.0/8}
      SMARTHOST_ADDRESS: ${SMTP_RELAY_HOST:-}
      SMARTHOST_PORT: ${SMTP_RELAY_PORT:-}
      SMARTHOST_USER: ${SMTP_RELAY_USER:-}
      SMARTHOST_PASSWORD: ${SMTP_RELAY_PASS:-}
      SMARTHOST_ALIASES: ${SMTP_RELAY_ALIASES:-}
    mem_limit: ${SMTP_RELAY_MEMORY_LIMIT:-512M}
    ports:
      - ${SMTP_RELAY_NODEPORT:-25}:25
    ## Deploy
    deploy:
      replicas: ${SMTP_RELAY_REPLICAS:-1}
      mode: ${SMTP_RELAY_SWARM_MODE:-replicated}
      resources:
        limits:
          memory: ${SMTP_RELAY_MEMORY_LIMIT:-512M}
      placement:
        constraints:
          - ${SMTP_RELAY_PLACEMENT_CONSTRAINTS:-node.role==manager}
      ports:
        - target: 25
          mode: host
          publish:
            - ${SMTP_RELAY_NODEPORT:-25}:25
