networks:
  default:
    name: ${DEFAULT_NETWORK:-dokploy-network}
    external: ${DEFAULT_NETWORK_EXTERNAL:-true}

services:
  smtp-relay-relay:
    image: ${SMTP_RELAY_IMAGE:-namshi/smtp:latest}
    x-pull-policy: always
    environment:
      TZ: ${TZ}
      MAILNAME: ${SMTP_RELAY_MAILNAME:-smtp.example.com}
      RELAY_NETWORKS: ${SMTP_RELAY_NETWORKS:-:192.168.31.0/16:10.16.0.0/8}
      SMARTHOST_ADDRESS: ${SMTP_RELAY_HOST}
      SMARTHOST_PORT: ${SMTP_RELAY_PORT}
      SMARTHOST_USER: ${SMTP_RELAY_USER}
      SMARTHOST_PASSWORD: ${SMTP_RELAY_PASS}
      SMARTHOST_ALIASES: ${SMTP_RELAY_ALIASES}
    ## Deploy
    deploy:
      replicas: ${SMTP_RELAY_REPLICAS:-1}
      mode: ${SMTP_RELAY_SWARM_MODE:-replicated}
      resources:
        limits:
          memory: ${SMTP_RELAY_MEMORY_LIMIT:-512M}
      placement:
        constraints:
          - ${SMTP_RELAY_PLACEMENT_CONSTRAINTS:-node.role==manager}
      ports:
        - target: 25
          mode: host
          publish:
            - ${SMTP_RELAY_NODEPORT:-25}:25
      labels:
        # traefik.enable: "true"
        # traefik.http.services.smtp.loadbalancer.server.port: 80
        # traefik.http.routers.smtp.entrypoints: ${SMTP_TRAEFIK_ENTRYPOINTS:-web}
        # traefik.http.routers.smtp.rule: Host(`${SMTP_DOMAIN:-smtp.example.com}`) && PathPrefix(`${SMTP_BASE_PATH:-/}`)
        # traefik.http.routers.smtp.service: smtp
        # traefik.http.routers.smtp.middlewares: "${SMTP_TRAEFIK_MIDDLEWARES:-}"
        # traefik.http.routers.smtp.tls: "${SMTP_TRAEFIK_TLS_ENABLED:-false}"
        # traefik.http.routers.smtp.tls.certresolver: ${SMTP_TRAEFIK_TLS_CERTRESOLVER:-letsencrypt}
        ## Homepage configuration
        homepage.group: ${SMTP_RELAY_HOMEPAGE_GROUP:-}
        homepage.name: ${SMTP_RELAY_HOMEPAGE_NAME:-smtp}
        homepage.icon: ${SMTP_RELAY_HOMEPAGE_ICON:-smtp.png}
        # homepage.href: ${SMTP_RELAY_HOMEPAGE_HREF:-http://smtp.example.com}
        homepage.description: ${SMTP_RELAY_HOMEPAGE_DESCRIPTION:-}
        # homepage.siteMonitor: ${SMTP_RELAY_HOMEPAGE_SITEMONITOR:-http://smtp.example.com}
        homepage.ping: ${SMTP_RELAY_HOMEPAGE_PING:-}


