## https://gethomepage.dev/installation/docker/

# name: dashboard # Not supported by Docker Swarm

services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    # container_name: homepage
    # ports:
      # - 3000:3000
    volumes:
      - ${HOMEPAGE_CONFIG_DIR:-homepage_config}:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    # pull_policy: always ## Not supported by Docker Swarm
    environment:
      - TZ
      - http_proxy
      - https_proxy
      - no_proxy
      - HOMEPAGE_ALLOWED_HOSTS=${HOMEPAGE_DOMAIN}

    # labels:
    #   - "traefik.enable=true"
    #   # HTTP router
    #   - "traefik.http.services.homepage.loadbalancer.server.port=3000"
    #   - "traefik.http.routers.homepage.rule=Host(`${HOMEPAGE_DOMAIN}`)"
    #   - "traefik.http.routers.homepage.service=homepage"
    #   - "traefik.http.routers.homepage.entrypoints=web"
    #   # HTTPS router
    #   - "traefik.http.routers.homepage-secure.rule=Host(`${HOMEPAGE_DOMAIN}`)"
    #   - "traefik.http.routers.homepage-secure.service=homepage"
    #   - "traefik.http.routers.homepage-secure.entrypoints=websecure"
    #   - "traefik.http.routers.homepage-secure.tls=true"


# networks:
#   default:
#     name: dokploy-network
#     external: true

volumes:
  homepage_config:
    driver: local
