
# networks:
#   default:
#     name: dokploy-network
#     external: true

# name: storage # Not supported by Docker Swarm
services:
  # S3 Client
  minio-client:
    image: minio/mc:latest
    restart: unless-stopped
    # pull_policy: always ## Not supported by Docker Swarm
    entrypoint: ["/bin/sh", "-c"]
    command: ["sleep infinity"]
    environment:
      - TZ
      - http_proxy
      - https_proxy
      - no_proxy
      - MINIO_SERVER_HOST
      - MINIO_SERVER_ACCESS_KEY
      - MINIO_SERVER_SECRET_KEY
    volumes:
      - ${MINIO_CLIENT_DATA_DIR:-minio_client_data}:/data

volumes:
  minio_client_data:
    driver: local
