# name: storage # Not supported by Docker Swarm
services:

  adguard:
    image: adguard/adguardhome
    restart: always
    # pull_policy: always
    # network_mode: host
    ports:
      # - 53:53/tcp
      - 53:53/udp
      # - 8880:80/tcp
      # - 8883:443/tcp
      # - 8300:3000/tcp
    volumes:
      - ${ADGUARD_CONFIG_DIR:-adguard_config}:/opt/adguardhome/conf
      - ${ADGUARD_WORK_DIR:-adguard_work}:/opt/adguardhome/work
    environment:
      - TZ
      - http_proxy
      - https_proxy
      - no_proxy
    privileged: true
    # cap_add:
    #   - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    labels:
      - traefik.enable=true
      - traefik.http.services.adguard.loadbalancer.server.port=80
      # HTTP
      - traefik.http.routers.adguard.entrypoints=web
      - traefik.http.routers.adguard.rule=Host(`${ADGUARD_DOMAIN}`)
      - traefik.http.routers.adguard.service=adguard
      # HTTPS
      - traefik.http.routers.adguard-secure.entrypoints=websecure
      - traefik.http.routers.adguard-secure.rule=Host(`${ADGUARD_DOMAIN}`)
      - traefik.http.routers.adguard-secure.service=adguard
      - traefik.http.routers.adguard-secure.tls=true
      - traefik.http.routers.adguard-secure.tls.certresolver=${ADGUARD_CERTIFICATE_RESOLVER:-default}
      # Homepage
      - homepage.group=${ADGUARD_HOMEPAGE_GROUP:-Dashboard}
      - homepage.name=${ADGUARD_HOMEPAGE_NAME:-AdGuard}
      - homepage.icon=${ADGUARD_HOMEPAGE_ICON:-adguard.png}
      - homepage.href=${ADGUARD_HOMEPAGE_HREF:-http://${ADGUARD_DOMAIN}/}

volumes:
  adguard_config:
    driver: local
  adguard_work:
    driver: local

networks:
  default:
    name: ${DEFAULT_NETWORK:-dokploy-network}
    external: true
