
networks:
  default:
    name: ${DEFAULT_NETWORK_NAME:-tpl-network}
    external: ${DEFAULT_NETWORK_EXTERNAL:-true}

volumes:
  tpl-volume:
    name: ${TPL_VOLUME_NAME:-tpl_volume}
    external: ${TPL_VOLUME_EXTERNAL:-false}

services:
  tpl:
    image: ${TPL_IMAGE_REGISTRY:-docker.io}/${TPL_IMAGE_PATH:-tpl/tpl}:${TPL_IMAGE_TAG:-latest}
    x-pull-policy: ${TPL_PULL_POLICY:-always}
    restart: ${TPL_RESTART:-unless-stopped}
    privileged: ${TPL_PRIVILEGED:-false}
    environment:
      - TZ=${TZ:-UTC}
      - TPL_IMAGE_TAG=${TPL_IMAGE_TAG:-latest}
      ## See .env.example for more environment variables
    env_file:
      - ${TPL_ENV_FILE:-.env}
    volumes:
      - ${TPL_HOST_VOLUME_PATH:-tpl-volume}:${TPL_CONTAINER_VOLUME_PATH:-/volumes/tpl}:z
      # - ${DOCKER_RUNTIME_SOCKET:-/var/run/docker.sock}:/var/run/docker.sock
    ## Deploy
    deploy:
      replicas: ${TPL_DEPLOY_REPLICAS:-1}
      mode: ${TPL_DEPLOY_SWARM_MODE:-replicated}
      placement:
        constraints:
          # Empty / unset → any Linux node (Swarm scheduler picks). Override to pin.
          - ${TPL_DEPLOY_PLACEMENT_CONSTRAINTS:-node.platform.os==linux}
