networks:
  default:
    name: ${DEFAULT_NETWORK_NAME:-dokploy-network}
    external: ${DEFAULT_NETWORK_EXTERNAL:-true}

services:
  logto:
    image: ${LOGTO_IMAGE:-ghcr.io/logto-io/logto:latest}
    restart: ${LOGTO_RESTART:-unless-stopped}
    privileged: ${LOGTO_PRIVILEGED:-false}
    entrypoint:
      - sh
      - -c
      - npm run cli db seed -- --swe && npm start
    env_file:
      - ${LOGTO_ENV_FILE:-.env.example}
    environment:
      - TZ=${TZ:-America/Toronto}
      - TRUST_PROXY_HEADER=${LOGTO_TRUST_PROXY_HEADER:-1}
      - DB_URL=${LOGTO_DB_URL:-postgres://logto:ChangeMe@dokploy-postgresql:5432/logto}
      - PORT=${LOGTO_PORT:-3001}
      - ADMIN_PORT=${LOGTO_ADMIN_PORT:-3002}
      - ENDPOINT=${LOGTO_ENDPOINT:-http://logto.example.com}
      - ADMIN_ENDPOINT=${LOGTO_ADMIN_ENDPOINT:-http://admin.logto.example.com}
    deploy:
      mode: ${LOGTO_DEPLOY_MODE:-replicated}
      replicas: ${LOGTO_DEPLOY_REPLICAS:-1}
      placement:
        constraints:
          - ${LOGTO_PLACEMENT_CONSTRAINTS:-node.platform.os==linux}
      restart_policy:
        condition: on-failure
        delay: 5s
      resources:
        limits:
          memory: ${LOGTO_MEMORY_LIMIT:-1G}
