networks:
  default:
    name: ${MINIO_CLIENT_NETWORK:-dokploy-network}
    external: ${MINIO_CLIENT_NETWORK_EXTERNAL:-true}

volumes:
  minio_client_data:
    name: ${MINIO_CLIENT_DATA_VOLUME_NAME:-minio_client_data}
    external: ${MINIO_CLIENT_DATA_VOLUME_EXTERNAL:-false}
  minio_client_logs:
    name: ${MINIO_CLIENT_LOGS_VOLUME_NAME:-minio_client_logs}
    external: ${MINIO_CLIENT_LOGS_VOLUME_EXTERNAL:-false}

services:
  minio-client:
    image: ${MINIO_CLIENT_IMAGE:-minio-client/minio-client:latest}
    volumes:
      - ${MINIO_CLIENT_DATA_DIR:-minio_client_data}:/data
      - ${DOCKER_RUNTIME_SOCKET:-/var/run/docker.sock}:/var/run/docker.sock
    # networks:
    #   - default
    environment:
      - TZ
      - http_proxy
      - https_proxy
      - no_proxy
    ## Deploy
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==${MINIO_CLIENT_PLACEMENT_CONSTRAINTS:-manager}
      labels:
        ## Homepage configuration
        homepage.group: ${MINIO_CLIENT_HOMEPAGE_GROUP:-Infra}
        homepage.name: ${MINIO_CLIENT_HOMEPAGE_NAME:-minio-client}
        homepage.icon: ${MINIO_CLIENT_HOMEPAGE_ICON:-minio-client.png}
        homepage.description: ${MINIO_CLIENT_HOMEPAGE_DESCRIPTION:-Minio Client is a platform for cli tool for s3 management.}



