
networks:
  default:
    name: ${PORTAINER_NETWORK:-dokploy-network}
    external: ${PORTAINER_NETWORK_EXTERNAL:-true}

volumes:
  portainer_data:
    name: ${PORTAINER_DATA_VOLUME_NAME:-portainer_data}
    external: ${PORTAINER_DATA_VOLUME_EXTERNAL:-false}
  # portainer_logs:
  #   name: ${PORTAINER_LOGS_VOLUME_NAME:-portainer_logs}
  #   external: ${PORTAINER_LOGS_VOLUME_EXTERNAL:-false}

services:
  portainer:
    image: ${PORTAINER_IMAGE:-portainer/portainer-ce:latest}
    # container_name: portainer
    restart: ${PORTAINER_RESTART:-unless-stopped}
    pull_policy: ${PORTAINER_PULL_POLICY:-always}
    volumes:
      - ${DOCKER_RUNTIME_SOCKET:-/var/run/docker.sock}:/var/run/docker.sock
      - ${PORTAINER_DATA_VOLUME_NAME:-portainer_data}:/data
    environment:
      - TZ
      - http_proxy
      - https_proxy
      - no_proxy
    labels:
      traefik.enable: "true"
      traefik.http.services.portainer.loadbalancer.server.port: 9000
      traefik.http.routers.portainer.entrypoints: ${PORTAINER_TRAEFIK_ENTRYPOINTS:-web}
      traefik.http.routers.portainer.rule: Host(`${PORTAINER_DOMAIN:-portainer.home}`) && PathPrefix(`${PORTAINER_TRAEFIK_PATH_PREFIX:-/}`)
      traefik.http.routers.portainer.service: portainer
      traefik.http.routers.portainer.middlewares: "${PORTAINER_TRAEFIK_MIDDLEWARES:-}"
      traefik.http.routers.portainer.tls: "${PORTAINER_TRAEFIK_TLS_ENABLED:-false}"
      traefik.http.routers.portainer.tls.certresolver: ${PORTAINER_TRAEFIK_TLS_CERTRESOLVER:-letsencrypt}
      ## Homepage configuration
      homepage.group: ${PORTAINER_HOMEPAGE_GROUP:-Infra}
      homepage.name: ${PORTAINER_HOMEPAGE_NAME:-Portainer}
      homepage.icon: ${PORTAINER_HOMEPAGE_ICON:-portainer.png}
      homepage.href: http://${PORTAINER_DOMAIN:-portainer.home}
      homepage.description: ${PORTAINER_HOMEPAGE_DESCRIPTION:-Portainer is a platform for managing Docker containers.}
