networks:
  default:
    name: ${JENKINS_AGENT_NETWORK:-dokploy-network}
    external: ${JENKINS_AGENT_NETWORK_EXTERNAL:-true}
volumes:
  jenkins_agent_home:
    name: ${JENKINS_AGENT_HOME_VOLUME_NAME:-jenkins_agent_home}
    external: ${JENKINS_AGENT_HOME_VOLUME_EXTERNAL:-false}
  jenkins_agent_workdir:
    name: ${JENKINS_AGENT_WORKDIR_VOLUME_NAME:-jenkins_agent_workdir}
    external: ${JENKINS_AGENT_WORKDIR_VOLUME_EXTERNAL:-false}
services:
  jenkins-agent:
    image: ${JENKINS_AGENT_IMAGE:-atelier.cen.umontreal.ca/jenkins/agent:latest}
    userns_mode: keep-id
    x-pull-policy: ${JENKINS_AGENT_PULL_POLICY:-if_not_present}
    restart: ${JENKINS_AGENT_RESTART:-unless-stopped}
    privileged: ${JENKINS_AGENT_PRIVILEGED:-true}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        HTTP_PROXY: ${HTTP_PROXY}
        HTTPS_PROXY: ${HTTPS_PROXY}
        NO_PROXY: ${NO_PROXY}
        USER_UID: ${JENKINS_AGENT_USER_UID:-501}
        USER_GID: ${JENKINS_AGENT_USER_GID:-100}
        USER_NAME: ${JENKINS_AGENT_USER_NAME:-admin}
        DOCKER_VERSION: ${DOCKER_VERSION:-27.3.1}
    # tty: true
    # stdin_open: true
    environment:
      - TZ=${TZ}
      - http_proxy=${HTTP_PROXY}
      - https_proxy=${HTTPS_PROXY}
      - no_proxy=${NO_PROXY}
      - HTTP_PROXY=${HTTP_PROXY}
      - HTTPS_PROXY=${HTTPS_PROXY}
      - NO_PROXY=${NO_PROXY}
      - USER_NAME=${JENKINS_AGENT_USER:-jenkins}
      - JENKINS_URL=${JENKINS_URL:-https://jenkins.example.com}
      - JENKINS_AGENT_NAME=${JENKINS_AGENT_NAME:-jenkins-agent}
      - JENKINS_SECRET=${JENKINS_SECRET}
      - JENKINS_AGENT_WORKDIR=${JENKINS_AGENT_WORKDIR:-/var/jenkins-agent}
      - JENKINS_WEB_SOCKET=${JENKINS_WEB_SOCKET:-true}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - CONTAINER_HOST=unix:///var/run/docker.sock
    volumes:
      - ${DOCKER_RUNTIME_SOCKET:-/var/run/docker.sock}:/var/run/docker.sock
      - ${JENKINS_AGENT_MOUNT_HOME_DIR:-jenkins_agent_home}:/home/${JENKINS_AGENT_USER_NAME:-admin}:z
      - ${JENKINS_AGENT_MOUNT_WORKDIR:-jenkins_agent_workdir}:${JENKINS_AGENT_WORKDIR:-/var/jenkins-agent}
    mem_limit: ${JENKINS_AGENT_MEMORY_LIMIT:-512M}
    ## Deploy
    deploy:
      replicas: ${JENKINS_AGENT_REPLICAS:-1}
      mode: ${JENKINS_AGENT_DEPLOY_MODE:-replicated}
      resources:
        limits:
          memory: ${JENKINS_AGENT_MEMORY_LIMIT:-512M}
      placement:
        constraints:
          - ${JENKINS_AGENT_PLACEMENT_CONSTRAINTS:-node.role==manager}
      labels:
        ## Homepage configuration
        homepage.enabled: ${JENKINS_AGENT_HOMEPAGE_ENABLED:-true}
        homepage.group: ${JENKINS_AGENT_HOMEPAGE_GROUP:-Infra}
        homepage.name: ${JENKINS_AGENT_HOMEPAGE_NAME:-Jenkins Agent}
        homepage.icon: ${JENKINS_AGENT_HOMEPAGE_ICON:-jenkins.png}
        homepage.description: ${JENKINS_AGENT_HOMEPAGE_DESCRIPTION:-}
    labels:
      ## Homepage configuration
      homepage.enabled: ${JENKINS_AGENT_HOMEPAGE_ENABLED:-true}
      homepage.group: ${JENKINS_AGENT_HOMEPAGE_GROUP:-Infra}
      homepage.name: ${JENKINS_AGENT_HOMEPAGE_NAME:-Jenkins Agent}
      homepage.icon: ${JENKINS_AGENT_HOMEPAGE_ICON:-jenkins.png}
      homepage.description: ${JENKINS_AGENT_HOMEPAGE_DESCRIPTION:-}
