networks:
  default:
    name: ${DEFAULT_NETWORK_NAME:-jenkins_agent_network}
    external: ${DEFAULT_NETWORK_EXTERNAL:-false}
volumes:
  jenkins_agent_home:
    name: ${JENKINS_AGENT_HOME_VOLUME_NAME:-jenkins_agent_home}
    external: ${JENKINS_AGENT_HOME_VOLUME_EXTERNAL:-false}
  jenkins_agent_workdir:
    name: ${JENKINS_AGENT_WORKDIR_VOLUME_NAME:-jenkins_agent_workdir}
    external: ${JENKINS_AGENT_WORKDIR_VOLUME_EXTERNAL:-false}
services:
  jenkins-agent:
    image: ${DOCKER_REGISTRY:-docker.io}/${JENKINS_AGENT_IMAGE_PATH:-jenkins/agent}:${JENKINS_AGENT_IMAGE_TAG:-latest}
    x-pull-policy: ${JENKINS_AGENT_PULL_POLICY:-always}
    restart: ${JENKINS_AGENT_RESTART:-unless-stopped}
    privileged: ${JENKINS_AGENT_PRIVILEGED:-true}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        HTTP_PROXY: ${HTTP_PROXY}
        HTTPS_PROXY: ${HTTPS_PROXY}
        NO_PROXY: ${NO_PROXY}
        USER_UID: ${JENKINS_AGENT_USER_UID:-501}
        USER_GID: ${JENKINS_AGENT_USER_GID:-100}
        USER_NAME: ${JENKINS_AGENT_USER_NAME:-admin}
        DOCKER_VERSION: ${DOCKER_VERSION:-27.3.1}
    # tty: true
    # stdin_open: true
    userns_mode: keep-id
    security_opt:
      - label=disable
    environment:
      - TZ=${TZ}
      - http_proxy=${HTTP_PROXY}
      - https_proxy=${HTTPS_PROXY}
      - no_proxy=${NO_PROXY}
      - HTTP_PROXY=${HTTP_PROXY}
      - HTTPS_PROXY=${HTTPS_PROXY}
      - NO_PROXY=${NO_PROXY}
      - JENKINS_URL=${JENKINS_SERVER_URL:-https://example.com/jenkins}
      - JENKINS_AGENT_NAME=${JENKINS_AGENT_NODE_NAME:-}
      - JENKINS_SECRET=${JENKINS_AGENT_NODE_SECRET:-}
      - JENKINS_AGENT_WORKDIR=${JENKINS_AGENT_NODE_WORKDIR:-/var/jenkins/agent}
      - JENKINS_WEB_SOCKET=${JENKINS_AGENT_WEB_SOCKET:-true}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - CONTAINER_HOST=unix:///var/run/docker.sock
    volumes:
      - ${DOCKER_RUNTIME_SOCKET:-/var/run/docker.sock}:/var/run/docker.sock
      - ${JENKINS_AGENT_HOME_HOST_PATH:-jenkins_agent_home}:/home/${JENKINS_AGENT_USER_NAME:-jenkins}:rw
      - ${JENKINS_AGENT_WORKDIR_HOST_PATH:-jenkins_agent_workdir}:${JENKINS_AGENT_NODE_WORKDIR:-/var/jenkins/agent}
    ## Deploy
    deploy:
      replicas: ${JENKINS_AGENT_DEPLOY_REPLICAS:-1}
      mode: ${JENKINS_AGENT_DEPLOY_MODE:-replicated}
      resources:
        limits:
          memory: ${JENKINS_AGENT_MEMORY_LIMIT:-512M}
      placement:
        constraints:
          - ${JENKINS_AGENT_DEPLOY_PLACEMENT_CONSTRAINTS:-node.labels.name==agent-1}
    #   labels:
    #     ## Homepage configuration
    #     homepage.enable: ${JENKINS_AGENT_HOMEPAGE_ENABLE:-true}
    #     homepage.group: ${JENKINS_AGENT_HOMEPAGE_GROUP:-Infra}
    #     homepage.name: ${JENKINS_AGENT_HOMEPAGE_NAME:-Jenkins Agent}
    #     homepage.icon: ${JENKINS_AGENT_HOMEPAGE_ICON:-jenkins.png}
    #     homepage.description: ${JENKINS_AGENT_HOMEPAGE_DESCRIPTION:-}
    # labels:
    #   ## Homepage configuration
    #   homepage.enable: ${JENKINS_AGENT_HOMEPAGE_ENABLE:-true}
    #   homepage.group: ${JENKINS_AGENT_HOMEPAGE_GROUP:-Infra}
    #   homepage.name: ${JENKINS_AGENT_HOMEPAGE_NAME:-Jenkins Agent}
    #   homepage.icon: ${JENKINS_AGENT_HOMEPAGE_ICON:-jenkins.png}
    #   homepage.description: ${JENKINS_AGENT_HOMEPAGE_DESCRIPTION:-}
